### ISSUE TITLE
There was an error fetching studies

### ISSUE THREAD

**Issue by protectedfor** [OHIF/Viewers#113]
Hello.

I have some problem displaying studies.

In console (Chrome) I get this error message:
```
For some reason we could not list the studies.
(anonymous) @ studylistResult.js:173
(anonymous) @ meteor.js?hash=27829e936d09beae3149ecfbf3332c42ccb1596f:1105
_maybeInvokeCallback @ livedata_connection.js:442
receiveResult @ livedata_connection.js:462
_livedata_result @ livedata_connection.js:1624
onMessage @ livedata_connection.js:277
(anonymous) @ stream_client_sockjs.js:174
_.each._.forEach @ underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149
self.socket.onmessage @ stream_client_sockjs.js:173
REventTarget.dispatchEvent @ sockjs-0.3.4.js:87
SockJS._dispatchMessage @ sockjs-0.3.4.js:1072
SockJS._didMessage @ sockjs-0.3.4.js:1130
that.ws.onmessage @ sockjs-0.3.4.js:1277
studylistResult.js:176 Error
    at Connection._livedata_result (livedata_connection.js:1624)
    at onMessage (livedata_connection.js:277)
    at stream_client_sockjs.js:174
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149)
    at SockJS.self.socket.onmessage (stream_client_sockjs.js:173)
    at SockJS.REventTarget.dispatchEvent (sockjs-0.3.4.js:87)
    at SockJS._dispatchMessage (sockjs-0.3.4.js:1072)
    at SockJS._didMessage (sockjs-0.3.4.js:1130)
    at WebSocket.that.ws.onmessage (sockjs-0.3.4.js:1277)
```
`Orthanc` server installed and works properly. I can access to it using this url: `http://localhost:8042`
I've uploaded some DICOM files and everything works great. But in OHIF viewer I can't display them. Why?

**Comment by protectedfor** [comment]
In the server console I get this:

```
./bin/orthanc.sh 
Starting Meteor server...
[[[[[ /var/www/Viewers-master/OHIFViewer ]]]]]

=> Started proxy.                             
=> Meteor 1.5.2.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
I20171011-14:10:21.159(6)? {                  
I20171011-14:10:21.204(6)?   "servers": {
I20171011-14:10:21.205(6)?     "dicomWeb": [
I20171011-14:10:21.206(6)?       {
I20171011-14:10:21.207(6)?         "name": "Orthanc",
I20171011-14:10:21.207(6)?         "wadoUriRoot": "http://localhost:8042/wado",
I20171011-14:10:21.208(6)?         "qidoRoot": "http://localhost:8042/dicom-web",
I20171011-14:10:21.209(6)?         "wadoRoot": "http://localhost:8042/dicom-web",
I20171011-14:10:21.209(6)?         "qidoSupportsIncludeField": false,
I20171011-14:10:21.210(6)?         "imageRendering": "wadouri",
I20171011-14:10:21.210(6)?         "requestOptions": {
I20171011-14:10:21.210(6)?           "auth": "orthanc:orthanc",
I20171011-14:10:21.211(6)?           "logRequests": true,
I20171011-14:10:21.211(6)?           "logResponses": false,
I20171011-14:10:21.212(6)?           "logTiming": true
I20171011-14:10:21.212(6)?         }
I20171011-14:10:21.212(6)?       }
I20171011-14:10:21.213(6)?     ]
I20171011-14:10:21.213(6)?   },
I20171011-14:10:21.214(6)?   "defaultServiceType": "dicomWeb",
I20171011-14:10:21.214(6)?   "dropCollections": true,
I20171011-14:10:21.215(6)?   "public": {
I20171011-14:10:21.215(6)?     "verifyEmail": false,
I20171011-14:10:21.216(6)?     "ui": {
I20171011-14:10:21.216(6)?       "studyListFunctionsEnabled": true,
I20171011-14:10:21.217(6)?       "leftSidebarOpen": false,
I20171011-14:10:21.218(6)?       "displaySetNavigationLoopOverSeries": false,
I20171011-14:10:21.219(6)?       "displaySetNavigationMultipleViewports": true,
I20171011-14:10:21.219(6)?       "autoPositionMeasurementsTextCallOuts": "TRLB",
I20171011-14:10:21.220(6)?       "displayEchoUltrasoundWorkflow": false,
I20171011-14:10:21.220(6)?       "showStackLoadingProgressBar": true,
I20171011-14:10:21.220(6)?       "cornerstoneRenderer": "webgl",
I20171011-14:10:21.220(6)?       "sortSeriesByIncomingOrder": false,
I20171011-14:10:21.221(6)?       "useMiddleSeriesInstanceAsThumbnail": true
I20171011-14:10:21.221(6)?     },
I20171011-14:10:21.221(6)?     "demoUserEnabled": true,
I20171011-14:10:21.222(6)?     "prefetch": {
I20171011-14:10:21.222(6)?       "displaySetCount": 1
I20171011-14:10:21.222(6)?     }
I20171011-14:10:21.223(6)?   }
I20171011-14:10:21.223(6)? }
I20171011-14:10:21.227(6)? Updating servers information from JSON configuration
=> Started your app.

=> App running at: http://localhost:3000/
I20171011-14:10:31.504(6)? http://localhost:8042/dicom-web/studies?includefield=00081030%2C00080060
W20171011-14:10:31.595(6)? (STDERR) Trace
W20171011-14:10:31.596(6)? (STDERR)     at Object.Services.QIDO.Studies (packages/ohif:study-list/server/services/qido/studies.js:102:18)
W20171011-14:10:31.597(6)? (STDERR)     at [object Object].Meteor.methods.StudyListSearch (packages/ohif:study-list/server/methods/studylistSearch.js:21:38)
W20171011-14:10:31.598(6)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
W20171011-14:10:31.599(6)? (STDERR)     at packages/ddp-server/livedata_server.js:719:19
W20171011-14:10:31.599(6)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20171011-14:10:31.600(6)? (STDERR)     at packages/ddp-server/livedata_server.js:717:40
W20171011-14:10:31.601(6)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20171011-14:10:31.602(6)? (STDERR)     at packages/ddp-server/livedata_server.js:715:46
W20171011-14:10:31.603(6)? (STDERR)     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
W20171011-14:10:31.604(6)? (STDERR)     at packages/ddp-server/livedata_server.js:559:43
W20171011-14:10:31.608(6)? (STDERR) Trace
W20171011-14:10:31.610(6)? (STDERR)     at [object Object].Meteor.methods.StudyListSearch (packages/ohif:study-list/server/methods/studylistSearch.js:26:22)
W20171011-14:10:31.610(6)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
W20171011-14:10:31.612(6)? (STDERR)     at packages/ddp-server/livedata_server.js:719:19
W20171011-14:10:31.613(6)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20171011-14:10:31.613(6)? (STDERR)     at packages/ddp-server/livedata_server.js:717:40
W20171011-14:10:31.614(6)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20171011-14:10:31.615(6)? (STDERR)     at packages/ddp-server/livedata_server.js:715:46
W20171011-14:10:31.616(6)? (STDERR)     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
W20171011-14:10:31.616(6)? (STDERR)     at packages/ddp-server/livedata_server.js:559:43
I20171011-14:10:31.918(6)? Exception while invoking method 'StudyListSearch' Error: We only support json but "" was sent by the server
I20171011-14:10:31.918(6)?     at Object.Future.wait (/home/protectedfor/.meteor/packages/meteor-tool/.1.5.0.1do6sm3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20171011-14:10:31.919(6)?     at packages/meteor.js:213:24
I20171011-14:10:31.920(6)?     at Object.DICOMWeb.getJSON (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:99:20)
I20171011-14:10:31.921(6)?     at Object.Services.QIDO.Studies (packages/ohif:study-list/server/services/qido/studies.js:98:31)
I20171011-14:10:31.921(6)?     at [object Object].Meteor.methods.StudyListSearch (packages/ohif:study-list/server/methods/studylistSearch.js:21:38)
I20171011-14:10:31.922(6)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20171011-14:10:31.923(6)?     at packages/ddp-server/livedata_server.js:719:19
I20171011-14:10:31.923(6)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20171011-14:10:31.924(6)?     at packages/ddp-server/livedata_server.js:717:40
I20171011-14:10:31.924(6)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20171011-14:10:31.925(6)?     - - - - -
I20171011-14:10:31.926(6)?     at ClientRequest.<anonymous> (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:51:22)
I20171011-14:10:31.927(6)?     at ClientRequest.g (events.js:260:16)
I20171011-14:10:31.927(6)?     at emitOne (events.js:77:13)
I20171011-14:10:31.928(6)?     at ClientRequest.emit (events.js:169:7)
I20171011-14:10:31.928(6)?     at HTTPParser.parserOnIncomingClient (_http_client.js:433:21)
I20171011-14:10:31.929(6)?     at HTTPParser.parserOnHeadersComplete (_http_common.js:97:23)
I20171011-14:10:31.929(6)?     at Socket.socketOnData (_http_client.js:322:20)
I20171011-14:10:31.930(6)?     at emitOne (events.js:77:13)
I20171011-14:10:31.931(6)?     at Socket.emit (events.js:169:7)
I20171011-14:10:31.931(6)?     at readableAddChunk (_stream_readable.js:153:18)
I20171011-14:10:51.140(6)? http://localhost:8042/dicom-web/studies?includefield=00081030%2C00080060

```

Where should I configure username / password for `Orthanc` server? Is there any default values?

**Comment by protectedfor** [comment]
Error disappeared. I've changed this lines:
```
        "qidoRoot": "http://localhost:8042/dicom-web",
        "wadoRoot": "http://localhost:8042/dicom-web",
```
to this:
```
        "qidoRoot": "http://localhost:8042",
        "wadoRoot": "http://localhost:8042",
```

Now OHIF viewer gives me this message: `No matching results`.
But in `Orthanc` server there is uploaded studies. Why it doesn't display them?

**Comment by swederik** [comment]
You shouldn't have to change the WADO / DICOMWeb URLs.

Do you have the Orthanc DICOMWeb plugin installed? Are you certain it's working?

If you go to this link http://localhost:8042/dicom-web/studies?includefield=00081030%2C00080060

and enter your username / password (orthanc/orthanc), do you get a list of studies?

**Comment by protectedfor** [comment]
No I don't get a list, I'm getting an error:
```
{
HttpError: "Not Found",
HttpStatus: 404,
Message: "Unknown resource",
Method: "GET",
OrthancError: "Unknown resource",
OrthancStatus: 17,
Uri: "/dicom-web/studies"
}
```

But if I go to this link: http://localhost:8042/studies?includefield=00081030%2C00080060

I'm getting an array of studies (now I have only one). Here is the response:
```
[
"0196a5a6-49c3e544-3a986265-5ffe1055-e26239dd"
]
```

**Comment by swederik** [comment]
That's a different API. You are hitting Orthanc's REST API. We do not support that, we only support DICOMWeb (and DIMSE, but that's another story). You need to install and set up the Orthanc DICOMWeb plugin. 

See https://bitbucket.org/sjodogne/orthanc-dicomweb/src

https://www.orthanc-server.com/static.php?page=dicomweb

**Comment by protectedfor** [comment]
I've compiled Orthanc DICOMWeb plugin and now need to reinstall Orthanc server because on my Ubuntu installation there is Orthanc version 1.0.0 But DICOMWeb plugin requires higher version. I've copiled Orthanc server and now can't run in, typing `Orthanc` in terminal shows me: 
```
The program 'Orthanc' is currently not installed. You can install it by typing:
sudo apt install orthanc
```
But if I'll run this command I'll install version 1.0.0. Question: How should I run compiled Orthanc server?

**Comment by swederik** [comment]
You need to add the path to the binary to the PATH environment variable.
Alternatively you can probably just do:

sudo make install

In the same place you ran make

On Oct 11, 2017 1:06 PM, "Andrey Fedotov" <notifications@github.com> wrote:

I've compiled Orthanc DICOMWeb plugin and now need to reinstall Orthanc
server because on my Ubuntu installation there is Orthanc version 1.0.0 But
DICOMWeb plugin requires higher version. I've copiled Orthanc server and
now can't run in, typing Orthanc in terminal shows me:

The program 'Orthanc' is currently not installed. You can install it by typing:
sudo apt install orthanc

But if I'll run this command I'll install version 1.0.0. Question: How
should I run compiled Orthanc server?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/OHIF/Viewers/issues/113#issuecomment-335775294>, or mute
the thread

**Comment by protectedfor** [comment]
Great! Thanks, it's works for me.

Now I'm going to make OHIF viewer access from production. What should I do to install Orthanc to my web server and provide access via static IP?

**Comment by swederik** [comment]
Typically you would put something like nginx or apache in front of it.
