### ISSUE TITLE
Returning to the Study List before viewport image finishes loading throws error in console

### ISSUE THREAD

**Issue by emfol** [OHIF/Viewers#1152]
## Returning to the Study List before viewport image finishes loading throws error in console

Image loads triggered by viewports (asyn) are not being canceled after the viewport element is unmounted. Handler are trying to set state of unmounted elements as the log message suggests:
![cornerstone-viewport-error](https://user-images.githubusercontent.com/1145367/68290768-46f03400-0067-11ea-889c-46763a150a0a.png)

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by jbocce** [comment]
I do not necessarily see the EXACT exceptions reported above, however I do see similar exceptions. In particular I see...

```
C:\dev\cornerstone3D-beta\packages\core\src\RenderingEngine\Viewport.ts:161 Uncaught (in promise) Error: Rendering engine has been destroyed
    at StackViewport.getRenderer (C:\dev\cornerstone3D-beta\packages\core\src\RenderingEngine\Viewport.ts:161:1)
    at StackViewport._updateActorToDisplayImageId (C:\dev\cornerstone3D-beta\packages\core\src\RenderingEngine\StackViewport.ts:1956:1)
    at StackViewport.successCallback (C:\dev\cornerstone3D-beta\packages\core\src\RenderingEngine\StackViewport.ts:1788:1)
    at C:\dev\cornerstone3D-beta\packages\core\src\RenderingEngine\StackViewport.ts:1813:1
```

```
C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at PanelStudyBrowserTracking (http://localhost:3000/extensions_measurement-tracking_src_index_tsx.js:1100:5)
    at bound WrappedPanelStudyBrowserTracking
    at div
    at SidePanel (http://localhost:3000/app.js:36088:5)
    at SidePanelWithServices (http://localhost:3000/extensions_default_src_index_ts.js:515:5)
    at ErrorBoundary (http://localhost:3000/app.js:181506:35)
    at ErrorBoundary (http://localhost:3000/app.js:29609:5)
    at div
    at div
    at ViewerLayoutWithServices (http://localhost:3000/extensions_default_src_index_ts.js:9865:69)
    at DndProvider (http://localhost:3000/app.js:149209:23)
    at DragAndDropProvider (http://localhost:3000/app.js:41913:5)
    at TrackedMeasurementsContextProvider (http://localhost:3000/extensions_measurement-tracking_src_index_tsx.js:70:5)
    at CombinedContextProvider (http://localhost:3000/app.js:17633:7)
    at ImageViewerProvider (http://localhost:3000/app.js:41979:5)
    at ModeRoute (http://localhost:3000/app.js:17537:5)
    at children
```

**Comment by sedghi** [comment]
@jbocce I don't see this happening again, can you let me know your steps

**Comment by sedghi** [comment]
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.
