### ISSUE TITLE
Build error on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by itarapov** [OHIF/Viewers#1386]
## Bug Report
yarn build fails on Ubuntu 18.04LTS

### Describe the Bug

Trying to follow the instructions here: https://docs.ohif.org/development/getting-started.html

I installed NPM and Node, installed Yarn

ran `yarn config set workspaces-experimental true`
running `yarn install`
and it fails with 

```[5/5] Building fresh packages...
[10/46] ? cypress
[-/46] ? waiting...
[-/46] ? waiting...
[-/46] ? waiting...
error /home/<username>/ohif/Viewers/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/<username>/ohif/Viewers/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.6.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.6.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v13.6.0/node-v13.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.6.0/node-v13.6.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.6.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.6.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/<username>/ohif/Viewers/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/<username>/ohif/Viewers/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/<username>/ohif/Viewers/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/<username>/.node-gyp/13.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/<username>/.node-gyp/13.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/<username>/ohif/Viewers/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/<username>/.node-gyp/13.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/<username>/ohif/Viewers/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/<username>/ohif/Viewers/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/<username>/.node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../src/stats.cc:19:
/home/<username>/.node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/<username>/.node-gyp/13.6.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/<username>/.node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/<username>/.node-gyp/13.6.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: Leaving directory '/home/<username>/ohif/Viewers/node_modules/sharp/build'
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/<username>/ohif/Viewers/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.0.0-1028-azure
gyp ERR! command "/usr/bin/node" "/home/<username>/ohif/Viewers/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/<username>/ohif/Viewers/node_modules/sharp
```

additionally, if I try npm rebuild it fails with

```
> sharp@0.22.1 install /home/<username>/ohif/Viewers/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using existing vendored libvips v8.7.4
make: Entering directory '/home/<username>/ohif/Viewers/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/<username>/.cache/node-gyp/13.6.0/include/node/node.h:63:0,
                 from ../src/stats.cc:19:
/home/<username>/.cache/node-gyp/13.6.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/<username>/.cache/node-gyp/13.6.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/<username>/.cache/node-gyp/13.6.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/<username>/.cache/node-gyp/13.6.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/home/<username>/ohif/Viewers/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.0.0-1028-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/<username>/ohif/Viewers/node_modules/sharp
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<username>/.npm/_logs/2020-01-20T10_56_30_082Z-debug.log
```

yarn version: 1.21.1
node version: 13.6.0
npm version: 6.13.4

### What steps can we follow to reproduce the bug?

Follow deployment instructions at https://docs.ohif.org/deployment/recipes/build-for-production.html or https://docs.ohif.org/development/getting-started.html

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by dannyrb** [comment]
node-gyp is notoriously a pain to build (in some situations). I believe this is outside the scope of what we intend to support -- you should be able to find helpful discussion on this specific issue via Google or StackOverflow.

I will leave this issue open until it goes stale should someone else choose to chime in.

**Comment by itarapov** [comment]
I was able to install by downgrading node per 

https://github.com/nodesource/distributions/blob/master/README.md

```
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_10.x | bash -
apt-get install -y nodejs
```

But build with Node v13 seems to be broken

**Comment by dannyrb** [comment]
Broken how? Steps to reproduce?

**Comment by sedghi** [comment]
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Comment by rouftom** [comment]
I had the same problem. I was using `node v20.0.0` with `nvm`. I downgraded to node `v16.19.0` and yarn install worked.
