### ISSUE TITLE
Permission denied when running Meteor

### ISSUE THREAD

**Issue by henryhe1** [OHIF/Viewers#231]
I am trying to deploy the viewer to a remote machine via ssh. I pulled the project from a repository, created a new persistent data volume, and added some DICOMs. However when I run the following command like I usually do on my local machine, I get an error: permission denied. Adding the `--allow-superuser` tag returns the same thing. 

`METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json`

```
/localhome/imagepro/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: EACCES: permission denied, open '/data1/venkat/imagepronew/Viewers/OHIFViewer/.meteor/local/.resolver-result-cache.json.lntsrx.8onjf'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.wrapper [as writeFile] (/tools/fs/files.js:1607:35)
    at Object.writeFileAtomically (/tools/fs/files.js:1069:11)
    at ProjectContext._saveResolverResultCache (/tools/project-context.js:615:11)
    at /tools/project-context.js:590:14
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:525:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:524:13)
    at /tools/project-context.js:296:9
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:286:18)
    at Profile.run (/tools/project-context.js:256:12)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.resolveConstraints (/tools/project-context.js:255:13)
    at /tools/runners/run-all.js:75:27
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at new Runner (/tools/runners/run-all.js:74:18)
    at Object.exports.run (/tools/runners/run-all.js:366:16)
    at Command.doRunCommand [as func] (/tools/cli/commands.js:415:17)
    at /tools/cli/main.js:1531:15

```

**Comment by henryhe1** [comment]
Update: was able to solve by changing ownership of the project directory from root to user. Turns out running `sudo git pull` is bad

`sudo chown -R user.group directory/`
for example: `sudo chown -R henry.henry imagepronew/`
