### ISSUE TITLE
Cloning and running yarn install fails

### ISSUE THREAD

**Issue by JonathanGilyadov** [OHIF/Viewers#2620]
> **Before Creating an issue**
>
> - Are you running the latest version? Yes
> - Are you reporting to the correct repository? Yes
> - Did you search existing issues? Yes

## Bug Report

Cloning and then running "yarn install" fails

### Describe the Bug

![image](https://user-images.githubusercontent.com/18733907/143254479-f1d619b7-be14-47a1-8de2-28346a82b905.png)

### What steps can we follow to reproduce the bug?

1, Clone the rep
2. Run yarn install

`error C:\Viewers\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Viewers\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Viewers\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Viewers\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.14.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Viewers\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Viewers\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Viewers\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Viewers\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Viewers\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Viewers\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Viewers\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Viewers\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Viewers\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Viewers\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Viewers\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Viewers\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Viewers\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Viewers\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Viewers\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Viewers\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Viewers\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Viewers\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Viewers\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (C:\Viewers\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:193:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Viewers\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Viewers\node_modules\node-sass
gyp ERR! node -v v15.14.0`

**Comment by ynakanishi1985** [comment]
I have very similar issues when I enter command "yarn install" .
Does anyone knows how to install without such warnings ?

![yarn_install_error1](https://user-images.githubusercontent.com/71856005/144057112-1562ba56-792e-4a42-8789-e8f14ccdb116.png)
![yarn_install_error2](https://user-images.githubusercontent.com/71856005/144057123-7b37b592-1f1c-4ddc-a9b6-ac068b7062ae.png)

**Comment by jovinson-ms** [comment]
The prereq you need is Node 16.x with optional Python and Visual Studio Build Tools installed ([webpack 4 has an issue](https://github.com/webpack/webpack/issues/14532) with Node 17.x).

**Comment by DraconPern** [comment]
I just tried on a clean install of ubuntu 20.04 with node LTS 16 and it fails because docz-plugin-css is being used. It's a 3 years old package that's pulling in really old version of node-sass.
