### ISSUE TITLE
Error: EPERM: operation not permitted, unlink 'C:\Users\Administrator\Views\Pack ages\ohif-measurements\.npm\package-new-12rovu8.dmf6\node_modules' on windows server 2012R2

### ISSUE THREAD

**Issue by itquota** [OHIF/Viewers#288]
Hello,
Nodejs version: 8.11.3
npm version: 5.6.0
meteor version: 1.7.0.3

I have tried so many commands:
meteor update --patch
meteor udpate
meteor
meteor --settings ../config/orthancDICOMWeb.json

I have tried the latest nod js and npm versions also 
I have tried build for production also but
I am getting this error on windows server 2012 R2 every time by following all the instructions and tutorial

=> Started proxy.
ohif:measurements: updating npm dependencies -- ajv, url, jspdf...
=> A patch (Meteor 1.7.0.5) for your current release is available!
   Update this project now with 'meteor update --patch'.
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.
windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, unlink 'C:\Users\Administrator\Views\Pack
ages\ohif-measurements\.npm\package-new-12rovu8.dmf6\node_modules'
 => awaited here:
    at Promise.await (C:\Users\Administrator\AppData\Local\.meteor\packages\mete
or-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\
promise_server.js:60:12)
    at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:32
5:7)
    at Object.meteorNpm.updateDependencies (C:\tools\isobuild\meteor-npm.js:131:
13)
    at Object.compile (C:\tools\isobuild\compiler.js:128:19)
    at C:\tools\isobuild\isopack-cache.js:354:30
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:309:18
)
    at Profile.time (C:\tools\isobuild\isopack-cache.js:243:16)
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:242:17
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:233
:20)
    at ensureLoaded (C:\tools\isobuild\isopack-cache.js:207:12)
    at C:\tools\isobuild\isopack-cache.js:235:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\Administrator\AppData\Local\.meteor\p
ackages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\und
erscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack-cache.js:234:11
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:233
:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Administrator\AppData\Local\.meteor\p
ackages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\und
erscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24
)
    at C:\tools\project-context.js:865:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:864:18)
    at C:\tools\project-context.js:296:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:286:18
)
    at Profile.run (C:\tools\project-context.js:278:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:277:13
)
    at C:\tools\runners\run-app.js:554:29
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:553:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12

Same OHIF viewer package with given nodejs,npm and meteor version is running well on windows 10 but not windows server 2012 R2
Please help me anybody to resolve this issue

Thanks

**Comment by SANTHOSH-SJ** [comment]
Encountering the same problem.. Does anyone have solution?

**Comment by Zaid-Safadi** [comment]
I have been getting this problem recently and having hard time finding the root cause. The difference is that you might get the error on different random packages but mostly on "ohif-cornerstone"

[Searching google for this error will show it is a very popular problem with node](https://www.google.com/search?q=EPERM%3A+operation+not+permitted%2C+unlink+node_modules+windows&rlz=1C1SQJL_enUS806US806&oq=EPERM%3A+operation+not+permitted%2C+unlink+node_modules+windows&aqs=chrome..69i57j69i58.6042j0j7&sourceid=chrome&ie=UTF-8)

Here are some ways I have been able to successfully pass this issue, it is random though so please report back what your experience is:
1. Disable your Anti-virus. In my case this is Windows Defender
2. Make sure no other node server is running in the background. Check the process in "Task Manager" and if you have Visual Studio opened make sure it is closed.
3. Keep running the build over and over and see if the package that has the error change or eventually the build will just work.
4. Try to restart your machine and start your build "meteor" after disabling your antivirus.

Please let me know if this works for you or you happen to find a different way.

**Comment by UgrBs** [comment]
It fails because the folder in error is not exist. For your case the folder's path is "C:\Users\Administrator\Views\Pack
ages\ohif-measurements.npm\package-new-12rovu8.dmf6\node_modules" 
If folder is not exist create it.
