### ISSUE TITLE
TMTV Mode : Not cross origin Isolated

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#2897]
Hi there, 

In the TMTV mode i have an error blocking OHIF to start saying the page is not cross-origin isolated,
It dosen't happen with the regular /viewer?=StudyInstanceUIDs= .... 

Seems to be related to the Float32Shared Array that might be the first use in OHIF.

Is there something that could be solved in OHIF itself to prevent this or do we need to specify CORS headers (https://web.dev/why-coop-coep/) (and thus would need to be documented)

Best regards

Salim

```
app.bundle.981458de0f2f6e453cb8.js:198903 Uncaught (in promise) Error: Your page is NOT cross-origin isolated, see https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated
    at createFloat32SharedArray (app.bundle.981458de0f2f6e453cb8.js:198903:15)
    at cornerstoneStreamingImageVolumeLoader (app.bundle.981458de0f2f6e453cb8.js:215780:26)
    at loadVolumeFromVolumeLoader (app.bundle.981458de0f2f6e453cb8.js:14200:20)
    at Module.createAndCacheVolume (app.bundle.981458de0f2f6e453cb8.js:14238:24)
    at CornerstoneCacheService._callee3$ (119.bundle.35c66264089fe20d326e.js:1160:37)
    at tryCatch (119.bundle.35c66264089fe20d326e.js:943:2404)
    at Generator._invoke (119.bundle.35c66264089fe20d326e.js:943:1964)
    at Generator.next (119.bundle.35c66264089fe20d326e.js:943:3255)
    at asyncGeneratorStep (119.bundle.35c66264089fe20d326e.js:945:103)
    at _next (119.bundle.35c66264089fe20d326e.js:947:194)
```

**Comment by pwespi** [comment]
See:

* https://www.cornerstonejs.org/docs/getting-started/scope#browser-support
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

These headers need to be set:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

**Comment by salimkanoun** [comment]
Yes, thanks for the input (i had fix the problem but forgot to close the issue, it will be however usefull for several other users, thx!)
