### ISSUE TITLE
Can't load multiframe XA

### ISSUE THREAD

**Issue by JeanRessouche** [OHIF/Viewers#2967]
## Bug Report

Version: v3, v2

### Describe the Bug

Impossible to use the viewer with XA (Coro) studies.

### What steps can we follow to reproduce the bug?

1. https://ohif.org/get-started
2. Select 'Use your own data'
3. Upload the enclosed sample (i reproduce with all my files :'()
https://filetransfer.io/data-package/DAye0RDw#link
4. Use the cine play button or scroll: the image count change, the image displayed stay the first one.

**Comment by jensen0914** [comment]
The sample image has no pixel data (i.e., is missing element 7fe0,0010). This is required for the SOP Class UID in the meta-data (X-Ray Angiographic Image Storage)

It does have an IconImageSequence (element 0088,0200) that shows it was probably created by Applicare/RadWorks/Version 5.0 and the pixel data element is buried in that sequence.

My guess this is not so much an OHIF Viewer issue but a non-standard DICOM image issue from your source. It does not display on some other DICOM viewers either (e.g., Horos) while some do seem to handle this non-standard image (e.g., Weasis).

**Comment by JeanRessouche** [comment]
Hello Todd, indeed, it should be images from GE CA1000, not a very recent device, but you know how long it can be for hospitals to move to more recent systems. Other viewers indeed appear to have no issues with it (playing with MedDream for exemple, perfect handling of it).

Do you believe that it's a complete no-go for ohif to implement the support of it? 
If so, ohif can't be used reliably, at least in cardiology and radiology in some countries (in France this GE system is used in the majority of hospitals and clinics)

**Comment by JeanRessouche** [comment]
Hello @jensen0914 , 

I try to figure out my options here and i have a difficulty:

> The sample image has no pixel data (i.e., is missing element 7fe0,0010).

By looking at it with dcmtk editor i can see the 07fe0,0010 tag, with the pixel data inside it and it can be exported with success.
![image](https://user-images.githubusercontent.com/8854025/193788281-a736bb5d-137a-4cd6-9b62-323956dd0f1b.png)

Do you believe that DCMTK is doing some internal magic to recover automatically the pixel data from the IconImageSequence ?

**Comment by jensen0914** [comment]
I was mistaken, the file does have pixel data - I'm not sure why my first run missed seeing that.

**Comment by jensen0914** [comment]
BTW - I can view this file when I load it in OHIF Viewer I build from this forked branch (jensen0914/Viewers](https://github.com/jensen0914/Viewers/tree/saincepacs-ohif-viewer), which is basically only a few commits behind OHIF Viewer v2 master branch (4.12.37 vs 4.12.41).
<img width="1470" alt="Screen Shot 2022-10-04 at 7 55 44 AM" src="https://user-images.githubusercontent.com/17097762/193826282-8ac8728d-7a09-4cba-8395-805db057e0df.png">

**Comment by jensen0914** [comment]
And in the v3 get started link:
<img width="1034" alt="Screen Shot 2022-10-04 at 8 05 21 AM" src="https://user-images.githubusercontent.com/17097762/193826724-5421b0d3-940e-4b75-9d95-401ac9bcf491.png">

**Comment by JeanRessouche** [comment]
Hi @jensen0914 , thanks again for your input.
i can also see it but i only see 1 frame. With this version you can play the entire sequence?
On my side playing or scrolling to display the next frame is not working.

**Comment by jensen0914** [comment]
In the v3 demo, I can only see the first frame even when scrolling. In my v2 build, I can see all of the frames when scrolling or using cine:
<img width="1475" alt="Screen Shot 2022-10-07 at 11 07 48 AM" src="https://user-images.githubusercontent.com/17097762/194598935-31ae3a07-daad-453c-91c1-a0931fdedf3c.png">

**Comment by arturojain** [comment]
Are you loading the data using JSON?

**Comment by JeanRessouche** [comment]
Thanks @jensen0914, then i'll try with the v2 again, building it myself as you did.
@arturojain nope, loading from a local .dcm file on the v3 demo version and from a dcm4chee source on my environment, with the same result.

**Comment by sedghi** [comment]
Could you kindly provide the data if it has been anonymized and you can confirm that there is no patient health information present in any of the headers or embedded within the pixel data?

**Comment by sedghi** [comment]
![CleanShot 2023-10-13 at 14 46 44](https://github.com/OHIF/Viewers/assets/7490180/5759ddf4-db13-46c0-b01c-215ade6894da)

**Comment by sedghi** [comment]
can you re-upload for us please

**Comment by makkourna** [comment]
Hello, I'm facing the same issue. I can't seem to run the Angiographic images (XA modalities). Has anyone found a solution or determined the cause of this problem?

Thanks!

**Comment by sedghi** [comment]
If you can share anonymized data, we may be able to review it.

**Comment by makkourna** [comment]
Thank you for your response.
This is a link of a study:
https://drive.google.com/drive/folders/1AK5bnlPyOW1-o7ck3ux4EEhCBX-fxFfV?usp=drive_link


Thanks,

Mohamad

**Comment by sedghi** [comment]
So I tried with our latest branch and it works in dicomweb at least using orthanc

![Image](https://github.com/user-attachments/assets/0a1790db-867e-4f4d-ac5b-661ad9ed33fd)


I'm wondering maybe it is just a local?

**Comment by sedghi** [comment]
I'm getting this error in drag and drop 

```
Error: Using multiple character sets is not supported: ,ISO 2022 IR 87,ISO 2022 IR 159
    at Function._read (dcmjs.es.js:10521:1)
    at Function.readFile (dcmjs.es.js:10597:1)
    at FileLoader.getDataset (dicomFileLoader.js:12:1)
    at FileLoaderService.getDataset (fileLoaderService.js:26:1)
    at processFile (filesToStudies.js:9:1)
    at async Promise.all (index 0)
    at async filesToStudies (filesToStudies.js:19:1)
    at async onDrop (Local.tsx:76:1)
```
