### ISSUE TITLE
Tracked markup SR hydration not working - exception thrown; tracked markup state incorrect

### ISSUE THREAD

**Issue by jbocce** [OHIF/Viewers#3105]
### Describe the Bug

In v3-stable, when doubling clicking to rehydrate an SR previously generated for tracked markups:
- an exception in thrown in the browser console
- the right-side Measurements table is NOT populated
- the top-left corner of the viewport indicates that the markups have not been restored
![image](https://user-images.githubusercontent.com/109477394/211548432-d1b4a5dd-c0ba-4723-8f4f-9947d1d4a72a.png)

### What steps can we follow to reproduce the bug?

1. Create and track a markup.
2. Click Create Report in the tracked measurements side panel.
3. Refresh the browser showing the same study as before.
4. Double click the SR corresponding to the tracked measurements made in step 2.
5. Click Yes in the prompt to continue tracking measurements.
6. The following exception is thrown in the browser console.

```
C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:38 Uncaught (in promise) TypeError: (0 , _ohif_extension_cornerstone_dicom_sr__WEBPACK_IMPORTED_MODULE_0__.default) is not a function
    at _callee$ (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:38:54)
    at tryCatch (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:2:1)
    at Generator.eval [as _invoke] (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:2:1)
    at Generator.eval [as next] (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:2:1)
    at asyncGeneratorStep (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:2:1)
    at _next (C:\dev\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\promptHydrateStructuredReport.js:2:1)
```

### Suspected Commit
Just prior to commit https://github.com/OHIF/Viewers/commit/9a03bde0ae98ed24ebf469da74490c0b51fc71f3 the functionality appears to work fine.

**Comment by sedghi** [comment]
@jbocce ditto

**Comment by jbocce** [comment]
No longer an issue in master.
