### ISSUE TITLE
Your application is crashing. Waiting for file change.

### ISSUE THREAD

**Issue by malaterre** [OHIF/Viewers#313]
It seems like LesionTracker is broken in git/master.

Steps:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```
gives me:

```
$ METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json
[[[[[ /tmp/Viewers/LesionTracker ]]]]]        

=> Started proxy.                             
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
=> A patch (Meteor 1.7.0.5) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
W20181114-13:52:28.105(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20181114-13:52:28.127(1)? (STDERR) While this implementation will work correctly, it is known to be
W20181114-13:52:28.128(1)? (STDERR) approximately three times slower than the native implementation.
W20181114-13:52:28.128(1)? (STDERR) In order to use the native implementation instead, run
W20181114-13:52:28.128(1)? (STDERR) 
W20181114-13:52:28.128(1)? (STDERR)   meteor npm install --save bcrypt
W20181114-13:52:28.128(1)? (STDERR) 
W20181114-13:52:28.129(1)? (STDERR) in the root directory of your application.
W20181114-13:52:28.129(1)? (STDERR) /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:475
W20181114-13:52:28.129(1)? (STDERR) }).run();
W20181114-13:52:28.129(1)? (STDERR)    ^
W20181114-13:52:28.129(1)? (STDERR) 
W20181114-13:52:28.129(1)? (STDERR) Error: The @babel/runtime npm package could not be found in your node_modules 
W20181114-13:52:28.130(1)? (STDERR) directory. Please run the following command to install it:
W20181114-13:52:28.130(1)? (STDERR) 
W20181114-13:52:28.130(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181114-13:52:28.130(1)? (STDERR) 
W20181114-13:52:28.130(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181114-13:52:28.130(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181114-13:52:28.130(1)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181114-13:52:28.131(1)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181114-13:52:28.131(1)? (STDERR)     at packages/babel-runtime.js:79:15
W20181114-13:52:28.131(1)? (STDERR)     at packages/babel-runtime.js:86:3
W20181114-13:52:28.131(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:411:36
W20181114-13:52:28.131(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181114-13:52:28.131(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:220:19
W20181114-13:52:28.131(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
W20181114-13:52:30.345(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20181114-13:52:30.346(1)? (STDERR) While this implementation will work correctly, it is known to be
W20181114-13:52:30.346(1)? (STDERR) approximately three times slower than the native implementation.
W20181114-13:52:30.346(1)? (STDERR) In order to use the native implementation instead, run
W20181114-13:52:30.346(1)? (STDERR) 
W20181114-13:52:30.346(1)? (STDERR)   meteor npm install --save bcrypt
W20181114-13:52:30.346(1)? (STDERR) 
W20181114-13:52:30.346(1)? (STDERR) in the root directory of your application.
W20181114-13:52:30.347(1)? (STDERR) /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:475
W20181114-13:52:30.347(1)? (STDERR) }).run();
W20181114-13:52:30.347(1)? (STDERR)    ^
W20181114-13:52:30.347(1)? (STDERR) 
W20181114-13:52:30.347(1)? (STDERR) Error: The @babel/runtime npm package could not be found in your node_modules 
W20181114-13:52:30.347(1)? (STDERR) directory. Please run the following command to install it:
W20181114-13:52:30.347(1)? (STDERR) 
W20181114-13:52:30.348(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181114-13:52:30.348(1)? (STDERR) 
W20181114-13:52:30.348(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181114-13:52:30.348(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181114-13:52:30.348(1)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181114-13:52:30.348(1)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181114-13:52:30.348(1)? (STDERR)     at packages/babel-runtime.js:79:15
W20181114-13:52:30.348(1)? (STDERR)     at packages/babel-runtime.js:86:3
W20181114-13:52:30.349(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:411:36
W20181114-13:52:30.349(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181114-13:52:30.349(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:220:19
W20181114-13:52:30.349(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
                                              
Unable to resolve some modules:

  "loglevel" in /tmp/Viewers/LesionTracker/client/log.js (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save loglevel          
                                              
W20181114-13:52:32.132(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20181114-13:52:32.132(1)? (STDERR) While this implementation will work correctly, it is known to be
W20181114-13:52:32.133(1)? (STDERR) approximately three times slower than the native implementation.
W20181114-13:52:32.133(1)? (STDERR) In order to use the native implementation instead, run
W20181114-13:52:32.133(1)? (STDERR) 
W20181114-13:52:32.133(1)? (STDERR)   meteor npm install --save bcrypt
W20181114-13:52:32.133(1)? (STDERR) 
W20181114-13:52:32.133(1)? (STDERR) in the root directory of your application.
W20181114-13:52:32.133(1)? (STDERR) /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:475
W20181114-13:52:32.134(1)? (STDERR) }).run();
W20181114-13:52:32.134(1)? (STDERR)    ^
W20181114-13:52:32.134(1)? (STDERR) 
W20181114-13:52:32.134(1)? (STDERR) Error: The @babel/runtime npm package could not be found in your node_modules 
W20181114-13:52:32.134(1)? (STDERR) directory. Please run the following command to install it:
W20181114-13:52:32.134(1)? (STDERR) 
W20181114-13:52:32.134(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181114-13:52:32.134(1)? (STDERR) 
W20181114-13:52:32.135(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181114-13:52:32.135(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181114-13:52:32.135(1)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181114-13:52:32.135(1)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181114-13:52:32.135(1)? (STDERR)     at packages/babel-runtime.js:79:15
W20181114-13:52:32.135(1)? (STDERR)     at packages/babel-runtime.js:86:3
W20181114-13:52:32.135(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:411:36
W20181114-13:52:32.135(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181114-13:52:32.135(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:220:19
W20181114-13:52:32.136(1)? (STDERR)     at /tmp/Viewers/LesionTracker/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

```

**Comment by malaterre** [comment]
Solved with a 
```
npm install -g npm@latest
npm cache verify
npm i 
```

sorry for the noise
