### ISSUE TITLE
[Bug] building Nginx + Image Archive recipe fails

### ISSUE THREAD

**Issue by Hasan-aga** [OHIF/Viewers#3423]
### description

I am following[ the guide ](https://v3-docs.ohif.org/deployment/nginx--image-archive/#cors-issues)to build ohif along with orthanc and nginx proxy. when I run `docker-compose up --build` from inside `Viewers/platform/viewer/.recipes/OpenResty-Orthanc` I get this error:
```
=> ERROR [builder 17/18] RUN yarn install                                                      0.5s
------                                                                                               
 > [builder 17/18] RUN yarn install:                                                                 
#0 0.358 yarn install v1.22.5                                                                        
#0 0.425 $ node preinstall.js                                                                        
#0 0.452 internal/modules/cjs/loader.js:818                                                          
#0 0.452   throw err;                                                                                
#0 0.452   ^                                                                                         
#0 0.452                                                                                             
#0 0.452 Error: Cannot find module '/usr/src/app/preinstall.js'
#0 0.452     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
#0 0.452     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
#0 0.452     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
#0 0.452     at internal/main/run_main_module.js:17:47 {
#0 0.452   code: 'MODULE_NOT_FOUND',
#0 0.452   requireStack: []
#0 0.452 }
#0 0.461 error Command failed with exit code 1.
#0 0.462 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
```
as far as I can tell, this error means that `preinstall.js` file is missing. this file exists inside `platform/` which docker does copies!
### Steps to Reproduce

1. switch to v3-stable branch
2. cd to `Viewers/platform/viewer/.recipes/OpenResty-Orthanc`
3. run `docker-compose up --build`

### The current behavior

docker fails with the above error.

### The expected behavior

I expect getting an image containing ohif that is linked to a local orthanc server.

### OS

tried this on macos ventura and ubuntu 22.10

### Node version

16.20.0

### Browser

-

**Comment by urosch** [comment]
Same here, I get the same error.
Using macos ventura on arm64 mac mini, if that might be problematic...

**Comment by Hasan-aga** [comment]
@urosch I spoke with the developers and they said that the docker images will be fixed when ohif v3 moves to master branch. until then you can try using node v16 in the dockerfile. here is my dockerfile for reference, let me know if it worked for you:
```
# docker-compose
# --------------
# This dockerfile is used by the `docker-compose.yml` adjacent file. When
# running `docker-compose build`, this dockerfile helps build the "webapp" image.
# All paths are relative to the `context`, which is the project root directory.
#
# docker build
# --------------
# If you would like to use this dockerfile to build and tag an image, make sure
# you set the context to the project's root directory:
# https://docs.docker.com/engine/reference/commandline/build/
#
#
# SUMMARY
# --------------
# This dockerfile has two stages:
#
# 1. Building the React application for production
# 2. Setting up our Nginx (OpenResty*) image w/ step one's output
#
# * OpenResty is functionally identical to Nginx with the addition of Lua out of
# the box.


# Stage 1: Build the application
FROM node:16.20.0 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Copy Files
COPY .docker /usr/src/app/.docker
COPY .webpack /usr/src/app/.webpack
COPY extensions /usr/src/app/extensions
COPY modes /usr/src/app/modes
COPY platform /usr/src/app/platform
COPY .browserslistrc /usr/src/app/.browserslistrc
COPY aliases.config.js /usr/src/app/aliases.config.js
COPY babel.config.js /usr/src/app/babel.config.js
COPY lerna.json /usr/src/app/lerna.json
COPY package.json /usr/src/app/package.json
COPY postcss.config.js /usr/src/app/postcss.config.js
COPY yarn.lock /usr/src/app/yarn.lock
ADD . /usr/src/app/


# ADD . /usr/src/app/
RUN yarn config set workspaces-experimental true
RUN yarn install

ENV APP_CONFIG=config/docker_openresty-orthanc.js
ENV PATH /usr/src/app/node_modules/.bin:$PATH

ENV QUICK_BUILD true
RUN yarn run build

# ADD . /usr/src/app/
# RUN yarn install
# RUN yarn run build:web


# Stage 2: Bundle the built application into a Docker container
# which runs openresty (nginx) using Alpine Linux
# LINK: https://hub.docker.com/r/openresty/openresty
FROM openresty/openresty:1.15.8.1rc1-0-alpine-fat

RUN mkdir /var/log/nginx
RUN apk add --no-cache openssl
RUN apk add --no-cache openssl-dev
RUN apk add --no-cache git
RUN apk add --no-cache gcc
# !!!
RUN luarocks install lua-resty-openidc

#
RUN luarocks install lua-resty-jwt
RUN luarocks install lua-resty-session
RUN luarocks install lua-resty-http
# !!!
RUN luarocks install lua-resty-openidc
RUN luarocks install luacrypto

# Copy build output to image
COPY --from=builder /usr/src/app/platform/viewer/dist /var/www/html

ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]

```

**Comment by Hasan-aga** [comment]
Just to be clear, I would love to open a pull request and fix the dockerfile myself but I am still having problems with the app even after patching the dockerfile. So until I figure out what's happening I can't do anything.

**Comment by urosch** [comment]
Add this to dockerfile:
`COPY preinstall.js /usr/src/app/preinstall.js
COPY version.txt /usr/src/app/version.txt
COPY commit.txt /usr/src/app/commit.txt
COPY runtime.txt /usr/src/app/runtime.txt`

*Then **if you are using arm64** add:`RUN apt-get -y clean && apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3 build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*`
(For arm64 there are certain packages being built from source and you need the python3 and build-essential packages.)

The build worked, now I have to solve the CORS config for nginx...

**Comment by urosch** [comment]
...and I also changed node version:
`FROM node:16.15.0-slim as builder`

**Comment by Hasan-aga** [comment]
@urosch  here is my nginx.conf, I have disabled the cors rule and increased the max body size
```
worker_processes 2;
error_log   /var/logs/nginx/mydomain.error.log;
pid /var/run/nginx.pid;
include /usr/share/nginx/modules/*.conf; # See /usr/share/doc/nginx/README.dynamic.

events {
    worker_connections 1024; ## Default: 1024
    use epoll; # http://nginx.org/en/docs/events.html
    multi_accept on; # http://nginx.org/en/docs/ngx_core_module.html#multi_accept
}

# Core Modules Docs:
# http://nginx.org/en/docs/http/ngx_http_core_module.html
http {
    include    '/usr/local/openresty/nginx/conf/mime.types';
    default_type application/octet-stream;

    keepalive_timeout 65;
    keepalive_requests 100000;
    tcp_nopush on;
    tcp_nodelay on;

    # lua_ settings
    #
    lua_package_path '/usr/local/openresty/lualib/?.lua;;';
    lua_shared_dict discovery 1m; # cache for discovery metadata documents
    lua_shared_dict jwks 1m;      # cache for JWKs
    # lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    variables_hash_max_size 2048;
    server_names_hash_bucket_size 128;
    server_tokens off;

    resolver 8.8.8.8 valid=30s ipv6=off;
    resolver_timeout 11s;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # Nginx `listener` block
    server {
        listen [::]:80 default_server;
        listen 80;
        # listen      443 ssl;
        access_log  /var/logs/nginx/mydomain.access.log;

        client_max_body_size 4G;


        # Domain to protect
        server_name 127.0.0.1 localhost; # mydomain.com;
        proxy_intercept_errors off;
        # ssl_certificate /etc/letsencrypt/live/mydomain.co.uk/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/mydomain.co.uk/privkey.pem;
        gzip on;
        gzip_types text/css application/javascript application/json image/svg+xml;
        gzip_comp_level 9;
        etag on;

        # https://github.com/bungle/lua-resty-session/issues/15
        set $session_check_ssi off;
        lua_code_cache off;
        set $session_secret Eeko7aeb6iu5Wohch9Loo1aitha0ahd1;
        set $session_storage cookie;

        server_tokens off; # Hides server version num

        # Reverse Proxy for `orthanc` admin
        #
        location /pacs-admin/ {

          proxy_http_version 1.1;

          proxy_set_header Host               $host;
          proxy_set_header X-Real-IP          $remote_addr;
          proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto  $scheme;

          expires           0;
          add_header        Cache-Control private;

          proxy_pass        http://orthanc:8042/;

          # add_header Access-Control-Allow-Origin *;

        }

        # Reverse Proxy for `orthanc` APIs (including DICOMWeb)
        #
        location /pacs/ {

          proxy_http_version 1.1;

          proxy_set_header Host               $host;
          proxy_set_header X-Real-IP          $remote_addr;
          proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto  $scheme;

          expires           0;
          add_header        Cache-Control private;

          proxy_pass        http://orthanc:8042/;

          # By default, this endpoint is protected by CORS (cross-origin-resource-sharing)
          # You can add headers to allow other domains to request this resource.
          # See the "Updating CORS Settings" example below

          # add_header Access-Control-Allow-Origin *;

        }

        # Do not cache sw.js, required for offline-first updates.
        location /sw.js {
          add_header Cache-Control "no-cache";
          proxy_cache_bypass $http_pragma;
          proxy_cache_revalidate on;
          expires off;
          access_log off;

          # add_header Access-Control-Allow-Origin *;
        }

        # Single Page App
        # Try files, fallback to index.html
        #
        location / {
          alias  /var/www/html/;
          index index.html;
          try_files $uri $uri/ /index.html;
          add_header Cache-Control "no-store, no-cache, must-revalidate";

          # add_header Access-Control-Allow-Origin *;
        }

        # EXAMPLE: Redirect server error pages to the static page /40x.html
        #
        # error_page 404 /404.html;
        #     location = /40x.html {
        # }

        # EXAMPLE: Redirect server error pages to the static page /50x.html
        #
        # error_page 500 502 503 504 /50x.html;
        #    location = /50x.html {
        # }
    }
}

```

**Comment by sedghi** [comment]
https://docs.ohif.org/2.0-deprecated/deployment/recipes/nginx--image-archive

**Comment by sedghi** [comment]
Seems like I actually did try it and it was working (since I captured video) before on v3

https://docs.ohif.org/deployment/nginx--image-archive
