### ISSUE TITLE
How do I run the OHIF Viewer with docker?

### ISSUE THREAD

**Issue by HowardLander** [OHIF/Viewers#360]
Hi all
I am new to both OHIF and docker, so please excuse what is probably a naive question (but answers still appreciated!).

I started running OHIF from the command line, but would prefer to use the docker image.  So I executed
```
sudo docker pull ohif/viewer
sudo docker run -p 3000:3000 ohif/viewer
```
But I didn't get the results I wanted.  Instead I got a series of 
```
[2019-02-27 14:23:02] PM2 log: Launching in no daemon mode
[2019-02-27 14:23:02] PM2 log: [Watch] Start watching ohif-viewer
[2019-02-27 14:23:02] PM2 log: Starting execution sequence in -fork mode- for app name:ohif-viewer id:0
[2019-02-27 14:23:02] PM2 log: App name:ohif-viewer id:0 online
The `stylus` package has been deprecated.
To continue using the last supported version
of this package, pin your package version to
2.513.14 (`meteor add stylus@=2.513.14`).
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at currentServer.js (packages/ohif:servers/both/collections/currentServer.js:10:23)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at index.js (packages/ohif:servers/both/collections/index.js:1:101)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at index.js (packages/ohif:servers/both/index.js:1:49)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at /app/bundle/programs/server/packages/ohif_servers.js:480:1
[2019-02-27 14:23:03] PM2 log: App [ohif-viewer] with id [0] and pid [17], exited with code [1] via signal [SIGINT]
[2019-02-27 14:23:03] PM2 log: Starting execution sequence in -fork mode- for app name:ohif-viewer id:0
[2019-02-27 14:23:03] PM2 log: App name:ohif-viewer id:0 online
The `stylus` package has been deprecated.
To continue using the last supported version
of this package, pin your package version to
2.513.14 (`meteor add stylus@=2.513.14`).
```
messages, followed by ignominious failure.  I've clearly done something pretty wrong: Could someone please either explain how to use this docker, or point me to the relevant documentation.  

Thanks much
Howard

**Comment by swederik** [comment]
The docker container needs to point to a MongoDB instance. For a simple deployment you would need to also run a Mongo container and specify the MONGO_URL as an environment variable, like we do here: https://github.com/OHIF/Viewers/blob/master/docker-compose.yml#L15

Sorry this isn't very well documented.

**Comment by HowardLander** [comment]
Ah.  That's very helpful. Thanks.  I'll try to work through it...

One other question: I changed one of the values in orthancDIMSE.json.  Do I put that change somehow in the docker compose file?

Howard

**Comment by swederik** [comment]
I think you will have to replace the app.json file inside the container to change settings: https://github.com/OHIF/Viewers/blob/master/dockerfile#L41

that's what we do when deploying via Kubernetes, at least.

**Comment by TZubiri** [comment]
Considering the point of containerizing is to provide atomic, standard, self sufficient, out of the box, units of software. Would it make sense to package the docker distribution with a mongo database by default?

**Comment by dannyrb** [comment]
I believe the heart of the original question has been answered. Please feel free to create a new issue if you encounter problems, have suggestions, or would like to discuss further ^_^

**Comment by chethanjjj** [comment]
Having a similar problem and those links do not work anymore. Can someone please provide working links?

**Comment by dannyrb** [comment]
https://github.com/OHIF/Viewers/tree/master/.docker
https://github.com/OHIF/Viewers/tree/master/platform/viewer/.recipes
