### ISSUE TITLE
[Bug] Segmentation not displaying over RGB images

### ISSUE THREAD

**Issue by Richard-Devine** [OHIF/Viewers#3613]
### Describe the Bug

I have 2 files, 1 a DICOM series the other a segmentation from the series, which both display perfectly on there own however when loading the segmentation to display over the DICOM series, the segmentation disappears and only displays the scan but is still listed in the Segmentation toolbar. Neither the console or display provide any errors for me to follow.

DICOM series: https://drive.google.com/drive/folders/1cNCy9PCBhqNRt3_lKqFLZaYWG61w-LQ8?usp=drive_link
Segmentation: https://drive.google.com/drive/folders/1jDPiZdaCwOhjB5OV0rypb1Y1AepaGl4b?usp=drive_link
OHIF v3.6.0

### Steps to Reproduce

1. Load the Study up in the OHIF viewer.
2. Double click the Seg icon.
3. Load the Segmentation.

### The current behavior

Segmentation disappears and only shows the scan with no segmentation overlay.

### The expected behavior

The segmentation overlays on top of the scan.

### OS

macOS

### Node version

v18.16.0

### Browser

Chrome v116.0.5845.96

**Comment by jbocce** [comment]
On my Windows 11 machine, matters appear much worse for this issue. As witnessed in the video below, when loading the SEG, the entire screen goes black and exceptions are displayed in the console. Also the warning `WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost` is displayed. Here are the various errors and exceptions...

```
C:\dev\Viewers\node_modules\@kitware\vtk.js\macros.js:57 Error compiling shader '#version 300 es
#define attribute in
#define textureCube texture
#define texture2D texture
#define textureCubeLod textureLod
#define texture2DLod textureLod


#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp int;
#else
precision mediump float;
precision mediump int;
#endif

/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkPolyDataVS.glsl

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

attribute vec4 vertexDC;

out vec3 vertexVCVSOutput;
uniform mat4 PCVCMatrix;

uniform float dcxmin;
uniform float dcxmax;
uniform float dcymin;
uniform float dcymax;

void main()
{
  // dcsmall is the device coords reduced to the
  // x y area covered by the volume
  vec4 dcsmall = vec4(
    dcxmin + 0.5 * (vertexDC.x + 1.0) * (dcxmax - dcxmin),
    dcymin + 0.5 * (vertexDC.y + 1.0) * (dcymax - dcymin),
    vertexDC.z,
    vertexDC.w);
  vec4 vcpos = PCVCMatrix * dcsmall;
  vertexVCVSOutput = vcpos.xyz/vcpos.w;
  gl_Position = dcsmall;
}
': 
```

```
C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:365 Uncaught TypeError: Cannot read properties of null (reading 'isAttributeUsed')
    at publicAPI.setMapperShaderParameters (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:365:1)
    at publicAPI.updateShaders (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:354:1)
    at publicAPI.renderPieceDraw (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:919:1)
    at publicAPI.renderPiece (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:990:1)
    at publicAPI.volumePass (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\VolumeMapper.js:88:1)
    at publicAPI.apply (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\SceneGraph\ViewNode.js:42:1)
    at publicAPI.traverse (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\SceneGraph\ViewNode.js:29:1)
    at publicAPI.traverseVolumePass (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\OpenGL\Volume.js:44:1)
    at publicAPI.traverse (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\SceneGraph\ViewNode.js:24:1)
    at publicAPI.traverse (C:\dev\Viewers\node_modules\@kitware\vtk.js\Rendering\SceneGraph\ViewNode.js:32:1)
```

https://github.com/OHIF/Viewers/assets/109477394/5442830e-c8fd-4136-8025-20185c04dcd2

**Comment by sedghi** [comment]
@Richard-Devine 
How have you created the segmentations? In the latest `master` commit I see there is only one slice at the very end.



![Image](https://github.com/OHIF/Viewers/assets/7490180/7d31a81a-d083-461e-b087-832a3e5ce6f1)


Regarding the OCT data. There is also seem to be somehow unusual. When I render MPR I see some of the data and some empty. 



I tried 3D Slicer, it shows some errors also for rendering

**Comment by james-hanks** [comment]
@Richard-Devine wondering if you would mind helping us reproduce this issue as per @sedghi comment above
