### ISSUE TITLE
[Bug] 3.7 QA Bug Report

### ISSUE THREAD

**Issue by james-hanks** [OHIF/Viewers#3685]
**Issues**

New Segmentation: Color of new segment doesn't change on first click 
- Create new segmentation
- Change color of fist segment
- Draw segment
- Color of segment drawn is the same as last selected segment
- Change color again, segment color now changes

**Feedback**
- Adjust range of mm radius slider on tool size. 0.01 is too small and 99 is too large. Also, I can't see anything drawn at 0.01 size even zoomed in

**Comment by jbocce** [comment]
Swapping in an already hydrated RTSTRUCT throws an exception and results in the destination viewport of the swap becoming blank. See the video below. The exception is...

```
C:\dev\Viewers\extensions\cornerstone\src\services\CornerstoneCacheService\CornerstoneCacheService.ts:227 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at CornerstoneCacheService._shouldRenderSegmentation (C:\dev\Viewers\extensions\cornerstone\src\services\CornerstoneCacheService\CornerstoneCacheService.ts:227:1)
    at CornerstoneCacheService.createViewportData (C:\dev\Viewers\extensions\cornerstone\src\services\CornerstoneCacheService\CornerstoneCacheService.ts:47:1)
    at loadViewportData (C:\dev\Viewers\extensions\cornerstone\src\Viewport\OHIFCornerstoneViewport.tsx:258:1)
    at C:\dev\Viewers\extensions\cornerstone\src\Viewport\OHIFCornerstoneViewport.tsx:304:1
    at invokePassiveEffectCreate (C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:3994:1)
    at invokeGuardedCallback (C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (C:\dev\Viewers\node_modules\react-dom\cjs\react-dom.development.js:23574:1)
    at unstable_runWithPriority (C:\dev\Viewers\node_modules\scheduler\cjs\scheduler.development.js:468:1)
```


https://github.com/OHIF/Viewers/assets/109477394/5817ffcc-d531-4f05-a5a3-82ccb0ecee7f

**Comment by jbocce** [comment]
Filtering by study date is hostile. It results in "Unable to query for studies at this time. Check your data source configuration or network connection" page getting displayed.


https://github.com/OHIF/Viewers/assets/109477394/108545bc-d480-497b-81ab-41244210072e

**Comment by jbocce** [comment]
After exiting MPR with the length tool selected, the w/l tool shows selected, yet a mouse drag draws a length tool. FYI, in 3.6, no tool shows selected, but the length tool is applied with a mouse drag.



https://github.com/OHIF/Viewers/assets/109477394/ba014e20-e524-4594-9487-70f93b6c9f54

**Comment by jbocce** [comment]
Double clicking in MPR with cross-hairs will eventually throws exceptions in the console - sometimes sooner than later, but it has consistently done so for me. However, everything appears to function fine after that point, but I do not know for sure.

Here is one of the exceptions...

```
<html>
<body>
<!--StartFragment--><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack:///node_modules/@cornerstonejs/tools/src/drawingSvg/setAttributesIfNecessary.ts:8" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">setAttributesIfNecessary.ts:8</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Error: &lt;rect&gt; attribute x: Expected length, "NaN".</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | (anonymous) | @ | setAttributesIfNecessary.ts:8
-- | -- | -- | --
  | ki | @ | setAttributesIfNecessary.ts:2
  | Fi | @ | drawHandles.ts:78
  | (anonymous) | @ | CrosshairsTool.ts:1320
  | Rs.renderAnnotation | @ | CrosshairsTool.ts:1117
  | (anonymous) | @ | triggerAnnotationRender.ts:188
  | (anonymous) | @ | triggerAnnotationRender.ts:202
  | Oi | @ | draw.ts:10
  | _triggerRender | @ | triggerAnnotationRender.ts:184
  | _renderFlaggedViewports | @ | triggerAnnotationRender.ts:93
  | requestAnimationFrame (async) |   |  
  | _render | @ | triggerAnnotationRender.ts:141
  | _setViewportsToBeRenderedNextFrame | @ | triggerAnnotationRender.ts:131
  | renderViewport | @ | triggerAnnotationRender.ts:70
  | Qi | @ | triggerAnnotationRender.ts:232
  | (anonymous) | @ | triggerAnnotationRen…orViewportIds.ts:14
  | Po | @ | triggerAnnotationRen…orViewportIds.ts:12
  | Rs.onCameraModified | @ | CrosshairsTool.ts:661
  | (anonymous) | @ | cameraModifiedEventDispatcher.ts:25
  | tm | @ | cameraModifiedEventDispatcher.ts:23
  | se | @ | triggerEvent.ts:37
  | triggerCameraModifiedEventIfNecessary | @ | Viewport.ts:1128
  | setCamera | @ | Viewport.ts:1103
  | resetCamera | @ | Viewport.ts:658
  | resetCamera | @ | VolumeViewport.ts:220
  | (anonymous) | @ | RenderingEngine.ts:601
  | _resizeVTKViewports | @ | RenderingEngine.ts:593
  | resize | @ | RenderingEngine.ts:332
  | resize | @ | CornerstoneViewportService.ts:103
  | (anonymous) | @ | OHIFCornerstoneViewport.tsx:141
  | (anonymous) | @ | utils.ts:50
  | di | @ | react-dom.production.min.js:130
  | Yo | @ | react-dom.production.min.js:184
  | Qs | @ | react-dom.production.min.js:269
  | Al | @ | react-dom.production.min.js:250
  | Ol | @ | react-dom.production.min.js:250
  | Pl | @ | react-dom.production.min.js:250
  | yl | @ | react-dom.production.min.js:243
  | (anonymous) | @ | react-dom.production.min.js:123
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:18
  | qa | @ | react-dom.production.min.js:122
  | Qa | @ | react-dom.production.min.js:123
  | Wa | @ | react-dom.production.min.js:122
  | gl | @ | react-dom.production.min.js:237
  | enqueueSetState | @ | react-dom.production.min.js:133
  | p.setState | @ | react.production.min.js:12
  | (anonymous) | @ | utils.ts:38
  | (anonymous) | @ | ResizeDetector.tsx:232
  | n.createResizeHandler | @ | ResizeDetector.tsx:227
  | p | @ | debounce.js:95
  | y | @ | debounce.js:144
  | v | @ | debounce.js:132
  | setTimeout (async) |   |  
  | (anonymous) | @ | debounce.js:103
  | b | @ | debounce.js:172

</span></div><!--EndFragment-->
</body>
</html>

```

https://github.com/OHIF/Viewers/assets/109477394/e583d883-efef-4c18-8007-3e3bb3d95a0e

**Comment by sedghi** [comment]
Fixed the first two
Three is tricky I'm investigating the MPR tool sync

The last one (crosshairs) having a hard time really reproducing it (was not successful even once)

**Comment by jbocce** [comment]
> Fixed the first two Three is tricky I'm investigating the MPR tool sync
> 
> The last one (crosshairs) having a hard time really reproducing it (was not successful even once)

@sedghi, for the crosshairs problem, I think double clicking at the "intersection point" of the crosshairs MIGHT have something to do with it. But I am not 100% certain.

**Comment by jbocce** [comment]
The hide all button is missing for basic viewer after hydrating a segmentation.

**Comment by jbocce** [comment]
Cannot launch MPR from MR SEG.

1. Launch https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.5962.99.1.2968617883.1314880426.1493322302363.3.0
2. Hydrate the SEG. Answer yes to hydrate when prompted.
3. Click the MPR button. The 1x3 layout displays with blank viewports. See the following exception.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at At._shouldRenderSegmentation (CornerstoneCacheService.ts:229:23)
    at At.createViewportData (CornerstoneCacheService.ts:47:14)
    at OHIFCornerstoneViewport.tsx:258:58
    at OHIFCornerstoneViewport.tsx:304:5
    at Ul (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qa (react-dom.production.min.js:122:325)
    at Nl (react-dom.production.min.js:261:308)
    at yl (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
```

**Comment by jbocce** [comment]
The hydrate SEG prompt banner sometimes stays after hydrating the SEG via the LOAD button...

https://github.com/OHIF/Viewers/assets/109477394/ef3fd983-afa2-400d-9100-27212a5710e8

**Comment by jbocce** [comment]
Hydrating two distinct SEGs does not result in two overlapping segmentations. At the very least the two segmentations are NOT displayed in the side panel - just one is shown.


https://github.com/OHIF/Viewers/assets/109477394/54d66a51-3fba-450f-8483-ef240bade3fe

**Comment by sedghi** [comment]
Reported bug https://github.com/Project-MONAI/MONAILabel/issues/1554#issuecomment-1751160712
