### ISSUE TITLE
[Bug] Error Message: Cannot read properties of undefined (reading 'withConfig')

### ISSUE THREAD

**Issue by muddasar-de** [OHIF/Viewers#3862]
### Describe the Bug

D:\XyCAD-V3\Viewers\node_modules\@xstate\react\es\useInterpret.js:65 Uncaught TypeError: Cannot read properties of undefined (reading 'withConfig')
    at D:\XyCAD-V3\Viewers\node_modules\@xstate\react\es\useInterpret.js:65:1
    at useConstant (D:\XyCAD-V3\Viewers\node_modules\@xstate\react\es\useConstant.js:5:1)
    at useIdleInterpreter (D:\XyCAD-V3\Viewers\node_modules\@xstate\react\es\useInterpret.js:56:1)
    at useMachine (D:\XyCAD-V3\Viewers\node_modules\@xstate\react\es\useMachine.js:33:1)
    at TrackedMeasurementsContextProvider (D:\XyCAD-V3\Viewers\extensions\measurement-tracking\src\contexts\TrackedMeasurementsContext\TrackedMeasurementsContext.tsx:158:1)
    at renderWithHooks (D:\XyCAD-V3\Viewers\node_modules\react-dom\cjs\react-dom.development.js:14985:1)
    at updateFunctionComponent (D:\XyCAD-V3\Viewers\node_modules\react-dom\cjs\react-dom.development.js:17356:1)
    at beginWork (D:\XyCAD-V3\Viewers\node_modules\react-dom\cjs\react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (D:\XyCAD-V3\Viewers\node_modules\react-dom\cjs\react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (D:\XyCAD-V3\Viewers\node_modules\react-dom\cjs\react-dom.development.js:3994:1)

![image](https://github.com/OHIF/Viewers/assets/75139126/e0681fa5-35be-4a02-b4d9-f575700f680b)

### Steps to Reproduce

...

### The current behavior

On route/Viewer, gives error of undefined withConfig

### The expected behavior

might be there should be a value of withConfig.

### OS

Windows 10

### Node version

latest

### Browser

chrome-letest

**Comment by sedghi** [comment]
is this still happening in most recent master branch commit?
