### ISSUE TITLE
Error: EPERM: operation not permitted, stat

### ISSUE THREAD

**Issue by 15895860324** [OHIF/Viewers#396]
Error: EPERM: operation not permitted, stat 'D:\JUSHA\PACS\JUSHI\Viewersdimse\OHIFViewer\.meteor\local\build\programs\server\node_modules'
    at Object.fs.statSync (fs.js:950:11)
    at Object.wrapper (C:\tools\fs\files.js:1558:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1693:27)
    at statOrNull (C:\tools\fs\files.js:287:15)
    at Object.files.cp_r (C:\tools\fs\files.js:458:16)
    at files.readdir.forEach.f (C:\tools\fs\files.js:479:13)
    at Array.forEach (<anonymous>)
    at Object.files.cp_r (C:\tools\fs\files.js:466:25)
    at files.readdir.forEach.f (C:\tools\fs\files.js:479:13)
    at Array.forEach (<anonymous>)
    at Object.files.cp_r (C:\tools\fs\files.js:466:25)
    at files.readdir.forEach.f (C:\tools\fs\files.js:479:13)
    at Array.forEach (<anonymous>)
    at Object.files.cp_r (C:\tools\fs\files.js:466:25)
    at Object.files.rename (C:\tools\fs\files.js:1747:13)
    at Object.files.renameDirAlmostAtomically.Profile [as renameDirAlmostAtomically] (C:\tools\fs\files.js:965:13)
    at Builder.complete (C:\tools\isobuild\builder.js:697:13)
    at C:\tools\isobuild\bundler.js:2766:13
    at C:\tools\isobuild\bundler.js:3074:22
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2907:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2854:32)
    at Object.withCache (C:\tools\fs\files.js:1658:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2854:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12

**Comment by dannyrb** [comment]
What steps did you take that lead to this output?

**Comment by 15895860324** [comment]
> What steps did you take that lead to this output?

After“meteor npm install”，then，“meteor --settings ../config/dcm4cheeDIMSE.json  --allow-superuser”(this step)

**Comment by dannyrb** [comment]
Is your issue resolved by the solution found here?: https://github.com/OHIF/Viewers/issues/231

**Comment by 15895860324** [comment]
> Is your issue resolved by the solution found here?: #231

sorry， i do not understand his action，can you explain it？
