### ISSUE TITLE
[Bug] Uncaught type error in demo server

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#3972]
### Describe the Bug

There is an error when the HP try to run, this is visible in the demo server : https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763

Uncaught TypeError: Cannot destructure property 'origin' of 'this.getImageData(...)' as it is undefined

Full error : Uncaught TypeError: Cannot destructure property 'origin' of 'this.getImageData(...)' as it is undefined.
    at v.getCurrentImageIdIndex (VolumeViewport.ts:359:13)
    at Yt.getPositionPresentation (CornerstoneViewportService.ts:237:42)
    at CornerstoneViewportService.ts:1030:33
    at Array.forEach (<anonymous>)
    at Yt.performResize (CornerstoneViewportService.ts:1029:15)
    at Yt.resize (CornerstoneViewportService.ts:119:12)
    at Object.callback (init.tsx:214:32)
    at pubSubServiceInterface.ts:85:16
    at Array.forEach (<anonymous>)
    at ee.l [as _broadcastEvent] (pubSubServiceInterface.ts:84:31)

### Steps to Reproduce

 Go here : https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=2.25.232704420736447710317909004159492840763

### The current behavior

No image loading

### The expected behavior

HP should run and display images

### OS

Linux

### Node version

20

### Browser

Chrome 122

**Comment by salimkanoun** [comment]
Fixed as well, Thx !
