### ISSUE TITLE
[Bug] Can't change HP stage if we change the current active study

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4070]
### Describe the Bug

In a multistage HP, if we change the displayed DICOM Study (for instance loading a pior scan), the HP stages becomes unavailable.

See video : 

https://github.com/OHIF/Viewers/assets/25229822/1c98c584-c6af-415c-8c6c-96ffd269a47b

### Steps to Reproduce

1. Go To : https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Load the "Lung Delays" study in the "Recent" tab of the image series selector
3. Try to change Stage by hitting ".", a "Hanging Protocol could not be applied" message appear

### The current behavior

Can't switch HP stage after changing the DICOM study being displayed

### The expected behavior

HP, including stage should work fully as long as the displayset are accepted, no matter if the rendered DICOM study has changed or not

### OS

Linux

### Node version

20

### Browser

Chrome latest

**Comment by salimkanoun** [comment]
@sedghi I still can reproduce this error following the initial description of the bug

And i found this error message in the console

`Error: Error: Error: Reused viewport details ctDisplaySet with ds 21d8ff75-c2b0-a9fe-1d8a-71a51be21713 not valid
    at fe.setProtocol (HangingProtocolService.ts:893:13)
    at Object.setHangingProtocol (commandsModule.ts:194:34)
    at deltaStage (commandsModule.ts:263:26)
    at Ke.runCommand (CommandsManager.ts:156:14)
    at HotkeysManager.ts:247:29
    at u (mousetrap.js:616:17)
    at S.t._handleKey (mousetrap.js:677:21)
    at S.handleKey (mousetrap.js:1008:32)
    at S.l (recordPlugin.js:58:22)
    at e.handleKey (recordPlugin.js:212:16)`

**Comment by sedghi** [comment]
I can't reproduce this any more on viewer-dev.ohif.org? can you share some videos maybe?

**Comment by salimkanoun** [comment]
Yes is still present in viewer-dev.ohif.org but the pull request of Bill in https://deploy-preview-4707--ohif-dev.netlify.app/ is correctly solving it !
