### ISSUE TITLE
[Bug] In Basic Viewer, Study Panel doesn't display thumbnails for different studies of the same patient.

### ISSUE THREAD

**Issue by VetsImaging** [OHIF/Viewers#4545]
### Describe the Bug

In Basic Viewer, Study Panel doesn't display thumbnails for different studies of the same patient.
And can't display image for different studies of the same patient in viewport.

![スクリーンショット 2024-11-24 135516](https://github.com/user-attachments/assets/bb9cf610-919d-4b5e-9ea3-352ee3f85d2f)
![スクリーンショット 2024-11-24 135550](https://github.com/user-attachments/assets/05b3e657-aff8-4f60-95b6-2336affc61bb)
![スクリーンショット 2024-11-24 102307](https://github.com/user-attachments/assets/b515272d-07f7-4d98-aea7-a52a94ea5f5f)
![スクリーンショット 2024-11-24 102336](https://github.com/user-attachments/assets/514bcc0d-6b2b-43ee-b3ee-4a3224a87b41)

### Steps to Reproduce

[ Prerequisites ]
1. git clone https://github.com/OHIF/Viewers.git
2. cd ./Viewers
3. switch branches/tags to v3.9.1
4. yarn install
5. yarn run dev:orthanc

* We don't modify any file in this repo.
* ORTHANC Version : 1.12.3 (installed by Orthanc Installer )
* Configuration files : default (not changed )
* Specifications of my local computer is as below ;
　CPU : intel core-i3 12100
　RAM : 16GB
　Storage : SSD 512TB

[ App Operation ]
1. Open a study with Basic Viewer.
2. Click "<" toggle button of another study.
3. Thumbnail are not displayed in the study panel.
4. Displayed error message as below ; 
　Something went wrong in Route /viewer.
　Sorry, something went wrong there. Try again.
5. Click "Show Detail" button, then displayed as below;
　Context: Route /viewer
　Error Message: IMAGE_REQUEST_TYPE is not defined
　Stack: ReferenceError: IMAGE_REQUEST_TYPE is not defined
![スクリーンショット 2024-11-24 135516](https://github.com/user-attachments/assets/c340d122-5a14-405a-84b4-ba4fd0793dcf)
 　at StudyPrefetcherService._stopPrefetching
(http://localhost:3000/app.js:134456:49)
    at StudyPrefetcherService._restartPrefetching
(http://localhost:3000/app.js:134465:12)
    at StudyPrefetcherService._syncWithActiveViewport (http://localhost:3000/app.js:134122:12)
    at Object.callback (http://localhost:3000/app.js:134068:130)
    at http://localhost:3000/app.js:136829:16
    at Array.forEach (<anonymous>)
    at DisplaySetService._broadcastEvent (http://localhost:3000/app.js:136828:31)
    at DisplaySetService.makeDisplaySets (http://localhost:3000/app.js:129502:14)
    at Object.callback (http://localhost:3000/app.js:121415:23)
    at http://localhost:3000/app.js:136829:16

### The current behavior

 Thumbnails for another study  for the same patient are not displayed in the study panel.

### The expected behavior

 Thumbnails for another study  for the same patient are displayed in the study panel.

### OS

Windows11pro

### Node version

Node v22.11.0, Yarn v1.22.22,  ORTHANC v1.12.1

### Browser

Chrome  131.0.6778.86

**Comment by sedghi** [comment]
Hmmm, i can't reproduce it in our demo at least

https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.25403.345050719074.3824.20170125095438.5

This one has two studies of the same patient. 

Can you try to reproduce it with our data?

**Comment by VetsImaging** [comment]
Thanks for your reply.

I have confirm that this issue doesn't happen on your demo site.

I will try to reproduce with your data.

Would you kindly tell us how can we get it ?

**Comment by sedghi** [comment]
https://github.com/OHIF/Viewers/blob/master/DATACITATION.md

**Comment by sedghi** [comment]
Any update on this?

**Comment by VetsImaging** [comment]
Thanks for your remind !
I will try to confirm on this weekend.

**Comment by VetsImaging** [comment]
I have tested it again with the latest version (v3.10.0 beta-63 ) and no problems like last time.
