### ISSUE TITLE
[Bug] Export DICOM SEG will fail at storeSegmentation

### ISSUE THREAD

**Issue by tkt9k2562** [OHIF/Viewers#4584]
### Describe the Bug

I can draw seg.

But it throws the bug when I export the seg.

Even I use the DICOM study provided by OHIF or myself on localhost , it occurs the same.

```
Context: Route /segmentation

Error Message: Cannot read properties of undefined (reading 'store')

Stack: TypeError: Cannot read properties of undefined (reading 'store')
at storeSegmentation (http://localhost:3005/extensions_cornerstone-dicom-seg_src_index_tsx.js:267:24)
```

![Image](https://github.com/user-attachments/assets/ffbab964-c548-4db6-9ba1-df93940ae7fd)

In addition , I noticed some warning when I `git clone & yarn install & yarn start`. 
Not sure if it is related or not

![Image](https://github.com/user-attachments/assets/77e4447a-296b-4413-a7aa-a7b62f430d9f)

![Image](https://github.com/user-attachments/assets/b4071b93-74a1-4b8d-9bc0-0e8b73d54ac4)

### Steps to Reproduce

1. Checkout the `master` branch or tag `v3.9.1`
2. Visit the anonymous study provided by OHIF
Or directly visit localhost : http://localhost/segmentation?StudyInstanceUIDs=1.2.826.0.1.3680043.2.1125.1.11608962641993666019702920539307840    
Or directly visit ohif-online-example : 
https://viewer.ohif.org/segmentation?StudyInstanceUIDs=1.2.826.0.1.3680043.2.1125.1.11608962641993666019702920539307840

![Image](https://github.com/user-attachments/assets/35be3b9d-eb07-4eb3-a33e-2f0cd0cb7813)

3. Draw the seg and click export button , will throw the bug
![Image](https://github.com/user-attachments/assets/95a95e8d-9de8-4d55-8d24-b02a0f436ba2)

### The current behavior

```
Context: Route /segmentation

Error Message: Cannot read properties of undefined (reading 'store')

Stack: TypeError: Cannot read properties of undefined (reading 'store')
at storeSegmentation (http://localhost:3005/extensions_cornerstone-dicom-seg_src_index_tsx.js:267:24)
```

![Image](https://github.com/user-attachments/assets/ffbab964-c548-4db6-9ba1-df93940ae7fd)

### The expected behavior

The DICOM SEG should be exported successfully.

### OS

macOS 14.4.1

### Node version

v18.20.0

### Browser

Chrome

**Comment by tkt9k2562** [comment]
In addition , I notice that the button `Download DICOM Seg` is work , while `Export DICOM Seg` is not.

What should be the difference between `Download` and `Export` ?

Does it mean export to somewhere ?

![Image](https://github.com/user-attachments/assets/75e3e9e5-fba3-43db-90b4-57ac4ffb0807)

**Comment by Bindhurasad** [comment]
I am also facing this issue,
Bug Report: Issue with Exporting DICOM SEG File

When creating a new segmentation, I can segment parts successfully. However, after completing the segmentation, I am unable to save the new segmentation file. Specifically, when clicking on "Export & Download → Export DICOM SEG", I encounter the following error:

Error Details:

Context: Route /segmentation
Error Message: No segmentation found
Stack Trace : storeSegmentation@http://localhost:3000/extensions_cornerstone-dicom-seg_src_index_tsx.js:249:15
![Image](https://github.com/user-attachments/assets/e88c6469-3c5c-459d-b7b6-d287ecfe0854)
![Image](https://github.com/user-attachments/assets/e39d9b4d-dcff-4dcb-a160-31e8fc4bcb2a)

**Comment by victormylle-dm** [comment]
I also have the same issue. I already made a GitHub issue two weeks ago and found out why this happened. https://github.com/OHIF/Viewers/issues/4549

**Comment by sedghi** [comment]
I think this works in viewerr.ohif.org (release branch), not in viewer-dev for some bug

**Comment by Bindhurasad** [comment]
Can you share the exact version number? As I mentioned, the SEG file downloaded properly.

**Comment by adriangaliana** [comment]
Hi @sedghi,

Although the fix involves moving to Node 20, I'm still encountering the same error in the latest master branch as well as in version 3.9.3.

Specifically, I’m unable to export DICOM SEG (though downloading it works without any issues).

The error I see in the console is:

```
Route /segmentation Error Boundary  
TypeError: Cannot read properties of undefined (reading 'store')  
    at storeSegmentation (commandsModule.ts:259:24)  
null Route /segmentation
```

Any insights on this would be greatly appreciated.

Thanks a lot!
