### ISSUE TITLE
[Bug] Touch feature not working for cobb angle

### ISSUE THREAD

**Issue by Rajat-Imme** [OHIF/Viewers#4590]
### Describe the Bug

I am using touch screen for measuring cobb angel but its not drawing the lines. Also some other features like contrast and zoom gets disabled when cobb angle is enabled

### Steps to Reproduce

Run the app 

Try drawing lines on touch screen preceded by enabling cobb angle

### The current behavior

Lines do not get drawn on touchscreen when cobb angle is enabled

### The expected behavior

Lines should be drawn to measure cobb angle

### OS

Windows 10

### Node version

20

### Browser

Chrome

**Comment by ramonribeiro96** [comment]
hi @Rajat-Imme , try this: https://github.com/OHIF/Viewers/issues/3952

**Comment by Rajat-Imme** [comment]
When i touch a pint on canvas then measurement starts followed by hovering of mouse to create line.

Cobb angle tool is not made in similar way to length annotation tool which allows to create line by dragging on the screen

**Comment by Rajat-Imme** [comment]
import { PublicToolProps, ToolProps } from '@cornerstonejs/tools/dist/types/types';
import { CobbAngleTool } from '@cornerstonejs/tools';
import { state } from '@cornerstonejs/tools/';
import {
  MouseUpEventType,
  MouseClickEventType,
} from '@cornerstonejs/tools/dist/types/types/EventTypes';

enum Events {
  MOUSE_DOWN = 'CORNERSTONE_TOOLS_MOUSE_DOWN',
  MOUSE_UP = 'CORNERSTONE_TOOLS_MOUSE_UP',
  MOUSE_DOWN_ACTIVATE = 'CORNERSTONE_TOOLS_MOUSE_DOWN_ACTIVATE',
  MOUSE_DRAG = 'CORNERSTONE_TOOLS_MOUSE_DRAG',
  MOUSE_MOVE = 'CORNERSTONE_TOOLS_MOUSE_MOVE',
  MOUSE_CLICK = 'CORNERSTONE_TOOLS_MOUSE_CLICK',
  MOUSE_DOUBLE_CLICK = 'CORNERSTONE_TOOLS_MOUSE_DOUBLE_CLICK',
  MOUSE_WHEEL = 'CORNERSTONE_TOOLS_MOUSE_WHEEL',
  TOUCH_START = 'CORNERSTONE_TOOLS_TOUCH_START',
  TOUCH_START_ACTIVATE = 'CORNERSTONE_TOOLS_TOUCH_START_ACTIVATE',
  TOUCH_PRESS = 'CORNERSTONE_TOOLS_TOUCH_PRESS',
  TOUCH_DRAG = 'CORNERSTONE_TOOLS_TOUCH_DRAG',
  TOUCH_END = 'CORNERSTONE_TOOLS_TOUCH_END',
  TOUCH_TAP = 'CORNERSTONE_TOOLS_TAP',
  TOUCH_SWIPE = 'CORNERSTONE_TOOLS_SWIPE',
}

class CustomCobbAngleTool extends CobbAngleTool {
  constructor(
    toolProps: PublicToolProps = {},
    defaultToolProps: ToolProps = {
      supportedInteractionTypes: ['Mouse', 'Touch'],
      configuration: {
        shadow: true,
        preventHandleOutsideImage: false,
        getTextLines: defaultGetTextLines,
        showArcLines: false,
      },
    }
  ) {
    super(toolProps, defaultToolProps);
  }

  _customMouseDownCallback = (evt: MouseUpEventType | MouseClickEventType) => {
    const { annotation } = this.editData;
    const { data } = annotation;
    if (!data.handles || !Array.isArray(data.handles.points)) {
      // Initialize the data when it's undefined or invalid
      data.handles = { points: [] };
      console.log('Initialized handles.points on touch down');
    }
    this._mouseDownCallback(evt);
  };

  _customMouseUpCallback = (evt: MouseUpEventType | MouseClickEventType) => {
    const { annotation } = this.editData;
    const { data } = annotation;
    if (!data.handles || !Array.isArray(data.handles.points)) {
      // Initialize the data when it's undefined or invalid
      data.handles = { points: [] };
      console.log('Initialized handles.points on touch down');
    }
    this._mouseUpCallback(evt);
  };

  _customMouseDragCallback = (evt: MouseUpEventType | MouseClickEventType) => {
    const { annotation } = this.editData;
    const { data } = annotation;
    if (!data.handles || !Array.isArray(data.handles.points)) {
      // Initialize the data when it's undefined or invalid
      data.handles = { points: [] };
      console.log('Initialized handles.points on touch down');
    }
    this._mouseDragCallback(evt);
  };

  _activateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;
    const { annotation } = this.editData;
    console.log('activate modify', annotation.data);
    element.addEventListener(Events.MOUSE_UP, this._customMouseUpCallback as EventListener);
    element.addEventListener(Events.MOUSE_DRAG, this._customMouseDragCallback as EventListener);
    element.addEventListener(Events.MOUSE_CLICK, this._customMouseDownCallback as EventListener);
    element.addEventListener(
      Events.TOUCH_END,
      this._customMouseUpCallback as EventListener // TOUCH_END -> MOUSE_UP
    );
    element.addEventListener(
      Events.TOUCH_DRAG,
      this._customMouseDragCallback as EventListener // TOUCH_DRAG -> MOUSE_DRAG
    );
    element.addEventListener(
      Events.TOUCH_TAP,
      this._customMouseDownCallback as EventListener // TOUCH_TAP -> MOUSE_CLICK
    );
  };

  _deactivateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;
    const { annotation } = this.editData;
    console.log('deactivate Modify', annotation.data);
    element.removeEventListener(Events.MOUSE_UP, this._customMouseUpCallback as EventListener);
    element.removeEventListener(Events.MOUSE_DRAG, this._customMouseDragCallback as EventListener);
    element.removeEventListener(Events.MOUSE_CLICK, this._customMouseUpCallback as EventListener);
    element.removeEventListener(
      Events.TOUCH_END,
      this._customMouseUpCallback as EventListener // TOUCH_END -> MOUSE_UP
    );
    element.removeEventListener(
      Events.TOUCH_DRAG,
      this._customMouseDragCallback as EventListener // TOUCH_DRAG -> MOUSE_DRAG
    );
    element.removeEventListener(
      Events.TOUCH_TAP,
      this._customMouseDownCallback as EventListener // TOUCH_TAP -> MOUSE_CLICK
    );
  };

  _activateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;
    const { annotation } = this.editData;
    console.log('activate draw', annotation.data);
    element.addEventListener(Events.MOUSE_UP, this._customMouseUpCallback as EventListener);
    element.addEventListener(Events.MOUSE_DRAG, this._customMouseDragCallback as EventListener);
    element.addEventListener(Events.MOUSE_MOVE, this._customMouseDragCallback as EventListener);
    element.addEventListener(Events.MOUSE_CLICK, this._customMouseUpCallback as EventListener);
    element.addEventListener(Events.MOUSE_DOWN, this._customMouseDownCallback as EventListener);

    element.addEventListener(
      Events.TOUCH_START,
      this._mouseDownCallback as EventListener // TOUCH_START -> MOUSE_DOWN
    );
    element.addEventListener(
      Events.TOUCH_END,
      this._mouseUpCallback as EventListener // TOUCH_END -> MOUSE_UP
    );
    element.addEventListener(
      Events.TOUCH_DRAG,
      this._mouseDragCallback as EventListener // TOUCH_DRAG -> MOUSE_DRAG
    );
    element.addEventListener(
      Events.TOUCH_TAP,
      this._mouseUpCallback as EventListener // TOUCH_TAP -> MOUSE_CLICK
    );
  };

  _deactivateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;
    const { annotation } = this.editData;
    console.log('deactivate draw', annotation.data);
    element.removeEventListener(Events.MOUSE_UP, this._customMouseUpCallback as EventListener);
    element.removeEventListener(Events.MOUSE_DRAG, this._customMouseDragCallback as EventListener);
    element.removeEventListener(Events.MOUSE_MOVE, this._customMouseDragCallback as EventListener);
    element.removeEventListener(Events.MOUSE_CLICK, this._customMouseUpCallback as EventListener);
    element.removeEventListener(Events.MOUSE_DOWN, this._customMouseDownCallback as EventListener);
    element.removeEventListener(
      Events.TOUCH_START,
      this._mouseDownCallback as EventListener // TOUCH_START -> MOUSE_DOWN
    );
    element.removeEventListener(
      Events.TOUCH_END,
      this._mouseUpCallback as EventListener // TOUCH_END -> MOUSE_UP
    );
    element.removeEventListener(
      Events.TOUCH_DRAG,
      this._mouseDragCallback as EventListener // TOUCH_DRAG -> MOUSE_DRAG
    );
    element.removeEventListener(
      Events.TOUCH_TAP,
      this._mouseUpCallback as EventListener // TOUCH_TAP -> MOUSE_CLICK
    );
  };
}

function defaultGetTextLines(data, targetId): string[] {
  const cachedVolumeStats = data.cachedStats[targetId];
  const { angle } = cachedVolumeStats;

  if (angle === null || angle === undefined) {
    return;
  }

  const textLines = [`${angle.toFixed(2)} ${String.fromCharCode(176)}`];

  return textLines;
}

CustomCobbAngleTool.toolName = 'CobbAngle';
export default CustomCobbAngleTool;


I have enabled touch features which is working

Issue is when i touch oin screent o add another measuremtn, it throws an error of undefined reading '0' 

Therefore an array of points is getting undefined

**Comment by Rajat-Imme** [comment]
import { CobbAngleTool } from '@cornerstonejs/tools';
import { Events } from '@cornerstonejs/tools/enums';
import { state } from '@cornerstonejs/tools';
class TouchCobbAngle extends CobbAngleTool {
  constructor(
    toolProps = {},
    defaultToolProps = {
      supportedInteractionTypes: ['Mouse', 'Touch'],
      configuration: {
        shadow: true,
        preventHandleOutsideImage: false,
        getTextLines: defaultGetTextLines,
        showArcLines: false,
      },
    }
  ) {
    super(toolProps, defaultToolProps);
    this._mouseUpCallback = this._mouseUpCallback.bind(this);
    this._mouseDragCallback = this._mouseDragCallback.bind(this);
    this._mouseDownCallback = this._mouseDownCallback.bind(this);
  }

  _activateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;
    element.addEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.addEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);
    element.addEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.addEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    element.addEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
    element.addEventListener(Events.TOUCH_START, this._mouseDownCallback);
  };

  _deactivateModif = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;
    element.removeEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.removeEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);

    // Touch event listeners removal
    element.removeEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    element.removeEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
  };

  _activateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;
    element.addEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.addEventListener(Events.MOUSE_MOVE, this._mouseDragCallback);
    element.addEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DOWN, this._mouseDownCallback);

    // Touch event listeners
    element.addEventListener(Events.TOUCH_END, this._mouseUpCallback); // Corresponding touch end to mouse up
    element.addEventListener(Events.TOUCH_DRAG, this._mouseDragCallback); // Corresponding touch drag to mouse drag
    element.addEventListener(Events.TOUCH_TAP, this._mouseUpCallback); // Corresponding touch tap to mouse click
    element.addEventListener(Events.TOUCH_START, this._mouseDownCallback); // Corresponding touch start to mouse down
  };

  deactivateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;
    element.removeEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.removeEventListener(Events.MOUSE_MOVE, this._mouseDragCallback);
    element.removeEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DOWN, this._mouseDownCallback);

    // Touch event listeners removal
    element.removeEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    element.removeEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_START, this._mouseDownCallback);
  };
}

function defaultGetTextLines(data, targetId) {
  const cachedVolumeStats = data.cachedStats[targetId];
  const { angle } = cachedVolumeStats;
  if (angle === undefined) {
    return;
  }
  const textLines = [`${angle.toFixed(2)} ${String.fromCharCode(176)}`];
  return textLines;
}
TouchCobbAngle.toolName = 'CobbAngle';
export default TouchCobbAngle;

**Comment by Rajat-Imme** [comment]
Mouse events are working as expected. Issue arises when i touch to modify the line, it starts a new measurement.

Also sometimes code breaks die to some undefined points on canvas

**Comment by Rajat-Imme** [comment]
Context: Route /viewer
Error Message: Cannot read properties of undefined (reading '0')
Stack: TypeError: Cannot read properties of undefined (reading '0')
    at TouchCobbAngle.distanceToLines (http://localhost:3000/extensions_cornerstone_src_index_tsx.js:308:203)
    at TouchCobbAngle.toolSelectedCallback (http://localhost:3000/extensions_cornerstone_src_index_tsx.js:339:16)
    at HTMLDivElement.touchStart (http://localhost:3000/vendors-node_modules_cornerstonejs_tools_dist_esm_index_js.js:4013:14)
    at triggerEvent (http://localhost:3000/app.js:22943:16)
    at triggerEventCallback (http://localhost:3000/vendors-node_modules_cornerstonejs_tools_dist_esm_index_js.js:5771:77)
    at _onTouchStart (http://localhost:3000/vendors-node_modules_cornerstonejs_tools_dist_esm_index_js.js:5832:31)
    at HTMLDivElement.touchStartListener (http://localhost:3000/vendors-node_modules_cornerstonejs_tools_dist_esm_index_js.js:5784:5)

**Comment by Rajat-Imme** [comment]
import { CobbAngleTool } from '@cornerstonejs/tools';
import { Events } from '@cornerstonejs/tools/enums';
import { state } from '@cornerstonejs/tools';
import { cursors } from '@cornerstonejs/tools';
import { getEnabledElement } from '@cornerstonejs/core';
import { triggerAnnotationRenderForViewportIds } from '@cornerstonejs/tools/utilities';
import { removeAnnotation } from '@cornerstonejs/tools/annotation/annotationState';
import { triggerAnnotationCompleted } from '@cornerstonejs/tools/annotation/helpers/state';
import { lineSegment } from '@cornerstonejs/tools/utilities/math/index';
import getViewportIdsWithToolToRender from '@cornerstonejs/tools/utilities/viewportFilters/getViewportIdsWithToolToRender';

class TouchCobbAngle extends CobbAngleTool {
  isModifying: boolean;
  constructor(
    toolProps = {},
    defaultToolProps = {
      supportedInteractionTypes: ['Mouse', 'Touch'],
      configuration: {
        shadow: true,
        preventHandleOutsideImage: false,
        getTextLines: defaultGetTextLines,
        showArcLines: false,
      },
    }
  ) {
    super(toolProps, defaultToolProps);
    this.isModifying = false;
  }
  _mouseDownCallback = evt => {
    const { annotation, handleIndex } = this.editData;
    const eventDetail = evt.detail;
    const { element, currentPoints } = eventDetail;
    const worldPos = currentPoints.world;
    const { data } = annotation;

    if (handleIndex === 1) {
      data.handles.points[1] = worldPos;
      this.editData.hasMoved =
        data.handles.points[1][0] !== data.handles.points[0][0] ||
        data.handles.points[1][1] !== data.handles.points[0][0];
      return;
    }
    if (handleIndex === 3) {
      data.handles.points[3] = worldPos;
      this.editData.hasMoved =
        data.handles.points[3][0] !== data.handles.points[2][0] ||
        data.handles.points[3][1] !== data.handles.points[2][0];
      this.angleStartedNotYetCompleted = false;
      return;
    }

    // Set default move behavior
    this.editData.hasMoved = false;
    cursors.elementCursor.hideElementCursor(element);

    // Update the points for drag operation
    data.handles.points[2] = data.handles.points[3] = worldPos;
    if (handleIndex !== undefined) {
      this.editData.handleIndex = data.handles.points.length - 1;
    }
    this.isDrawing = true;
  };

  _mouseUpCallback = evt => {
    const eventDetail = evt.detail;
    const { element } = eventDetail;
    const { annotation, viewportIdsToRender, newAnnotation, hasMoved } = this.editData;
    const { data } = annotation;

    // Do nothing if no movement has occurred and it's a new annotation
    if (newAnnotation && !hasMoved) {
      return;
    }

    // Handle angle logic if necessary
    if (this.angleStartedNotYetCompleted && data.handles.points.length < 4) {
      cursors.elementCursor.resetElementCursor(element);
      this.editData.handleIndex = data.handles.points.length;
      // console.log('first line made', this.editData);
      return;
    }

    // Reset the state after modification is done
    this.angleStartedNotYetCompleted = false;
    data.handles.activeHandleIndex = null;

    // Deactivate both modify and draw modes to finalize the action
    this._deactivateModify(element);
    this._deactivateDraw(element);

    // Reset the cursor state
    cursors.elementCursor.resetElementCursor(element);

    // const enabledElement = getEnabledElement(element);
    // const { renderingEngine } = enabledElement;

    // If the annotation is outside the image boundaries, remove it
    if (this.isHandleOutsideImage && this.configuration.preventHandleOutsideImage) {
      removeAnnotation(annotation.annotationUID);
    }

    // Trigger rendering
    triggerAnnotationRenderForViewportIds(viewportIdsToRender);

    // Mark the annotation as completed if new
    if (newAnnotation) {
      triggerAnnotationCompleted(annotation);
    }
    // this.editData = null;
    this.isDrawing = false;
  };

  _mouseDragCallback = evt => {
    const eventDetail = evt.detail;
    const {
      annotation,
      viewportIdsToRender,
      handleIndex,
      movingTextBox,
      isNearFirstLine,
      isNearSecondLine,
    } = this.editData;
    const { data } = annotation;

    // Handle dragging of text box or line handles
    if (movingTextBox) {
      const { deltaPoints } = eventDetail;
      const worldPosDelta = deltaPoints.world;
      const { textBox } = data.handles;
      const { worldPosition } = textBox;
      worldPosition[0] += worldPosDelta[0];
      worldPosition[1] += worldPosDelta[1];
      worldPosition[2] += worldPosDelta[2];
      textBox.hasMoved = true;
    } else if (handleIndex === undefined && (isNearFirstLine || isNearSecondLine)) {
      const { deltaPoints } = eventDetail;
      const worldPosDelta = deltaPoints.world;
      const points = data.handles.points;

      // Handle movement of lines
      if (isNearFirstLine) {
        const firstLinePoints = [points[0], points[1]];
        firstLinePoints.forEach(point => {
          point[0] += worldPosDelta[0];
          point[1] += worldPosDelta[1];
          point[2] += worldPosDelta[2];
        });
      } else if (isNearSecondLine) {
        const secondLinePoints = [points[2], points[3]];
        secondLinePoints.forEach(point => {
          point[0] += worldPosDelta[0];
          point[1] += worldPosDelta[1];
          point[2] += worldPosDelta[2];
        });
      }
      annotation.invalidated = true;
    } else {
      // Default case: update the current handle's position
      const { currentPoints } = eventDetail;
      const worldPos = currentPoints.world;
      if (handleIndex !== undefined) {
        data.handles.points[handleIndex] = [...worldPos];
      }

      annotation.invalidated = true;
    }

    // Indicate that movement has occurred
    this.editData.hasMoved = true;

    // const enabledElement = getEnabledElement(element);

    // console.log('mouse drag', this.editData);
    triggerAnnotationRenderForViewportIds(viewportIdsToRender);
  };

  _activateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;
    element.addEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.addEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);

    element.addEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.addEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    // element.addEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
  };

  _deactivateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;
    element.removeEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    element.removeEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);

    // Touch event listeners removal
    element.removeEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    // element.removeEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
  };

  _activateDraw = (element: HTMLDivElement) => {
    if (this.isModifying) {
      return;
    }
    state.isInteractingWithTool = true;
    element.addEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    // element.addEventListener(Events.MOUSE_MOVE, this._mouseDragCallback);
    // element.addEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);
    element.addEventListener(Events.MOUSE_DOWN, this._mouseDownCallback);

    // Touch event listeners
    element.addEventListener(Events.TOUCH_END, this._mouseUpCallback); // Corresponding touch end to mouse up
    element.addEventListener(Events.TOUCH_DRAG, this._mouseDragCallback); // Corresponding touch drag to mouse drag
    // element.addEventListener(Events.TOUCH_TAP, this._mouseUpCallback); // Corresponding touch tap to mouse click
    element.addEventListener(Events.TOUCH_START, this._mouseDownCallback); // Corresponding touch start to mouse down
  };

  _deactivateDraw = (element: HTMLDivElement) => {
    console.log('deactivate draw');
    state.isInteractingWithTool = false;
    element.removeEventListener(Events.MOUSE_UP, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DRAG, this._mouseDragCallback);
    // element.removeEventListener(Events.MOUSE_MOVE, this._mouseDragCallback);
    // element.removeEventListener(Events.MOUSE_CLICK, this._mouseUpCallback);
    element.removeEventListener(Events.MOUSE_DOWN, this._mouseDownCallback);

    // Touch event listeners removal
    element.removeEventListener(Events.TOUCH_END, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_DRAG, this._mouseDragCallback);
    // element.removeEventListener(Events.TOUCH_TAP, this._mouseUpCallback);
    element.removeEventListener(Events.TOUCH_START, this._mouseDownCallback);
  };
  distanceToLines = ({ viewport, points, canvasCoords, proximity }) => {
    if (!Array.isArray(points) || points.length !== 4) {
      return;
    }

    const [point1, point2, point3, point4] = points;
    const canvasPoint1 = viewport.worldToCanvas(point1);
    const canvasPoint2 = viewport.worldToCanvas(point2);
    const canvasPoint3 = viewport.worldToCanvas(point3);
    const canvasPoint4 = viewport.worldToCanvas(point4);
    const line1 = {
      start: {
        x: canvasPoint1[0],
        y: canvasPoint1[1],
      },
      end: {
        x: canvasPoint2[0],
        y: canvasPoint2[1],
      },
    };
    const line2 = {
      start: {
        x: canvasPoint3[0],
        y: canvasPoint3[1],
      },
      end: {
        x: canvasPoint4[0],
        y: canvasPoint4[1],
      },
    };
    const distanceToPoint = lineSegment.distanceToPoint(
      [line1.start.x, line1.start.y],
      [line1.end.x, line1.end.y],
      [canvasCoords[0], canvasCoords[1]]
    );
    const distanceToPoint2 = lineSegment.distanceToPoint(
      [line2.start.x, line2.start.y],
      [line2.end.x, line2.end.y],
      [canvasCoords[0], canvasCoords[1]]
    );
    let isNearFirstLine = false;
    let isNearSecondLine = false;
    if (distanceToPoint <= proximity) {
      isNearFirstLine = true;
    } else if (distanceToPoint2 <= proximity) {
      isNearSecondLine = true;
    }
    return {
      distanceToPoint,
      distanceToPoint2,
      isNearFirstLine,
      isNearSecondLine,
    };
  };
  toolSelectedCallback = (evt, annotation, interactionType, canvasCoords, proximity = 15) => {
    const eventDetail = evt.detail;
    const { element } = eventDetail;
    annotation.highlighted = true;
    const viewportIdsToRender = getViewportIdsWithToolToRender(element, this.getToolName());
    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement;
    // Validate canvasCoords
    if (!Array.isArray(canvasCoords) || canvasCoords.length < 2) {
      const { currentPoints } = evt.detail;
      canvasCoords = [currentPoints.canvas[0], currentPoints.canvas[1]];
    }
    const { isNearFirstLine, isNearSecondLine } = this.distanceToLines({
      viewport,
      points: annotation.data.handles.points,
      canvasCoords,
      proximity,
    });
    this.editData = {
      annotation,
      viewportIdsToRender,
      movingTextBox: false,
      isNearFirstLine,
      isNearSecondLine,
    };
    this._activateModify(element);
    cursors.elementCursor.hideElementCursor(element);
    triggerAnnotationRenderForViewportIds(viewportIdsToRender);
    evt.preventDefault();
  };

  isPointNearTool = (element, annotation, canvasCoords, proximity) => {
    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement;
    const { data } = annotation;
    const { distanceToPoint, distanceToPoint2 } = this.distanceToLines({
      viewport,
      points: data.handles.points,
      canvasCoords,
      proximity,
    });
    if (distanceToPoint <= proximity || distanceToPoint2 <= proximity) {
      return true;
    }
    return false;
  };
}

function defaultGetTextLines(data, targetId) {
  const cachedVolumeStats = data.cachedStats[targetId];
  const { angle } = cachedVolumeStats;
  if (angle === undefined) {
    return;
  }
  const textLines = [`${angle.toFixed(2)} ${String.fromCharCode(176)}`];
  return textLines;
}
TouchCobbAngle.toolName = 'CobbAngle';
export default TouchCobbAngle;
