### ISSUE TITLE
[Bug] Infinite loop in TMTV mode

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4636]
### Describe the Bug

There is an infinite loop in the TMTV causing a freeze then an error message

`app.bundle.a6e79b5e27bebec65b26.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at a (triggerEvent.js:10:16)
    at M.resetCamera (VolumeViewport.js:276:13)
    at M.applyViewOrientation (BaseVolumeViewport.js:250:18)
    at M.setOrientation (VolumeViewport.js:152:18)
    at M.setViewReference (BaseVolumeViewport.js:540:22)
    at M.setViewReference (BaseVolumeViewport.js:541:22)
    at M.setViewReference (BaseVolumeViewport.js:541:22)
    at M.setViewReference (BaseVolumeViewport.js:541:22)
    at M.setViewReference (BaseVolumeViewport.js:541:22)
    at M.setViewReference (BaseVolumeViewport.js:541:22)`

### Steps to Reproduce

1. go to https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
2. Once image loaded, turn the MIP with the scroll wheel
3. Double click on the CT viewport to make it toogle one up
4. Double click to exit the toogle one up
5. The error occurs and console shows infinite loop related to camera after a freeze

### The current behavior

Throws error

### The expected behavior

Should avoid infinit loop

### OS

Windows

### Node version

Node 20

### Browser

Chrome 131

**Comment by sedghi** [comment]
Hmm it is indeed related to MIP manipulation

**Comment by YiannisTheocharakis** [comment]
Will try to figure out what is causing the issue here and return with my findings.

**Comment by sedghi** [comment]
This is done thanks to @YiannisTheocharakis
