### ISSUE TITLE
Installation issue: npm-6.9.1.tgz request failed

### ISSUE THREAD

**Issue by tiimoS** [OHIF/Viewers#635]
Clones the project and ran `yarn install` from within the project's root directory. 
During installation, I get the following error: 
`error An unexpected error occurred: "https://registry.yarnpkg.com/npm/-/npm-6.9.1.tgz: Request failed \"404 Not Found\"".`

The trace from the yarn-error.logs:
`Trace: 
  Error: https://registry.yarnpkg.com/npm/-/npm-6.9.1.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.17.0/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.17.0/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.17.0/libexec/lib/cli.js:66893:16)
      at Request.emit (events.js:203:13)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.17.0/libexec/lib/cli.js:141316:10)
      at ClientRequest.emit (events.js:208:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
      at TLSSocket.socketOnData (_http_client.js:452:22)
      at TLSSocket.emit (events.js:203:13)`

I am using the master branch and the[ latest documentation](https://docs.ohif.org/essentials/getting-started.html) to install v2.0. 
yarn start inherently fails with exit code 127. 
Thanks for the support!

**Comment by swederik** [comment]
That's pretty weird...

- Do you have something like LittleSnitch running that could be blocking your requests?
- Are you behind a proxy?

This issue seems to have some ideas:

https://github.com/yarnpkg/yarn/issues/1565

**Comment by tiimoS** [comment]
> Do you have something like LittleSnitch running that could be blocking your requests?
no, I am not using LittleSnitch or similar, and am also not behind any proxy. I can successfully ping registry.yarnpkg.com. Already tried reinstalling node.js, deleting any proxy config, resetting npm registry settings etc. The only thing that worked now is renaming the yarn.lock file.

**Comment by swederik** [comment]
Sounds like there must be something wrong with our lockfile. That URL definitely doesn't exist, but I have no idea how that got in there.

**Comment by gzt036** [comment]
I solved in after a day by removing yarn.lock. All other options including resetting npm registery did nothing.

**Comment by dannyrb** [comment]
In general, blowing away the lockfile should do the trick. It's only _really_ important for making sure the code we're committing/developing triggers an identical/expected build. A good check list:

- Make sure `yarn` versions match
- Try running with `--frozen-lockfile`
- 💥 the lock file and try again
- Create an issue, like you've done here
