### ISSUE TITLE
Unable to build OHIF viewer 0.50.7

### ISSUE THREAD

**Issue by ranasrule** [OHIF/Viewers#799]
I'm unable to build OHIF viewer 0.50.7. I get problems at the **yarn install** command. Please see output below of build process....

```
Microsoft Windows [Version 10.0.17763.720]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7>yarn config set workspaces-experimental true
yarn config v1.17.3
success Set "workspaces-experimental" to "true".
Done in 0.09s.

C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7>yarn install
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@babel/runtime@7.5.5" is incompatible with requested version "@babel/runtime@7.1.2"
warning Resolution field "@babel/runtime@7.5.5" is incompatible with requested version "@babel/runtime@7.4.3"
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@1.x".
warning " > eslint-config-react-app@4.0.1" has unmet peer dependency "@typescript-eslint/parser@1.x".
warning " > eslint-config-react-app@4.0.1" has incorrect peer dependency "babel-eslint@10.x".
warning " > @ohif/core@0.50.2" has unmet peer dependency "cornerstone-core@^2.2.8".
warning " > @ohif/core@0.50.2" has unmet peer dependency "cornerstone-tools@^3.9.0".
warning " > @ohif/core@0.50.2" has unmet peer dependency "cornerstone-wado-image-loader@^3.0.0".
warning " > @ohif/core@0.50.2" has unmet peer dependency "dicom-parser@^1.8.3".
warning " > @ohif/i18n@0.50.1" has unmet peer dependency "i18next@^17.0.3".
warning " > @ohif/i18n@0.50.1" has unmet peer dependency "i18next-browser-languagedetector@^3.0.1".
warning " > @ohif/i18n@0.50.1" has unmet peer dependency "react-i18next@^10.11.0".
warning " > @ohif/ui@0.50.1" has incorrect peer dependency "@ohif/i18n@^0.2.3".
warning " > @ohif/ui@0.50.1" has unmet peer dependency "i18next@^17.0.3".
warning " > @ohif/ui@0.50.1" has unmet peer dependency "react-i18next@^10.11.0".warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "cornerstone-core@^2.2.8".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "cornerstone-math@^0.1.8".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "cornerstone-tools@^3.1.0".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "cornerstone-wado-image-loader@^3.0.0".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "dcmjs@^0.3.8".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "dicom-parser@^1.8.3".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "hammerjs@^2.0.8".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "prop-types@^15.6.2".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "react-redux@^6.0.0".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "react-resize-detector@^3.4.0".
warning " > @ohif/extension-cornerstone@0.50.1" has unmet peer dependency "redux@^4.0.1".
warning " > @ohif/extension-dicom-html@0.50.1" has unmet peer dependency "dcmjs@^0.3.3".
warning " > @ohif/extension-dicom-html@0.50.1" has unmet peer dependency "prop-types@^15.6.2".
warning " > @ohif/extension-dicom-pdf@0.50.1" has unmet peer dependency "dicom-parser@^1.8.3".
warning " > @ohif/extension-dicom-pdf@0.50.1" has unmet peer dependency "prop-types@^15.6.2".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "cornerstone-core@^2.2.8".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "cornerstone-wado-image-loader@^3.0.0".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "dcmjs@^0.4.7".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "dicom-parser@^1.8.3".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "i18next@^17.0.3".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "i18next-browser-languagedetector@^3.0.1".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "prop-types@^15.7.2".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "react-i18next@^10.11.0".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "react-redux@^7.1.0".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "react-resize-detector@^4.2.0".
warning " > @ohif/extension-vtk@0.50.3" has unmet peer dependency "redux@^4.0.1".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/ui > react-dnd-touch-backend@0.8.3" has incorrect peer dependency "react-dnd@^7.0.0".warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "cornerstone-core@^2.2.8".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "cornerstone-math@^0.1.8".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "cornerstone-tools@^3.1.0".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "cornerstone-wado-image-loader@^2.2.3".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "dicom-parser@^1.8.3".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "hammerjs@^2.0.8".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-cornerstone > react-cornerstone-viewport@0.1.30" has unmet peer dependency "react-resize-detector@^3.4.0".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/ui > docz-plugin-css > docz-core > react-docgen-typescript-loader@3.1.1" has unmet peer dependency "typescript@*".
warning "workspace-aggregator-e94120cc-25b4-4766-b418-0d5465ab0fa0 > @ohif/extension-vtk > vtk.js@9.7.0" has unmet peer dependency "wslink@^0.1.8".
[5/5] Building fresh packages...
[-/13] ⠈ waiting...
[7/13] ⠈ cypress
[-/13] ⠈ waiting...
[-/13] ⠁ waiting...
error C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at callback (C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\graceful-fs\polyfills.js:295:20)
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RAW\\Desktop\\Viewers--ohif-viewer-0.50.7\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\RAW\Desktop\Viewers--ohif-viewer-0.50.7\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0




```

**Comment by dannyrb** [comment]
I'm not 100% sure I follow the python and node-gyp requirements/output. I see different output when I clone a clean/new version of this repo and follow the install steps laid out in the readme. Try from a clean copy of the repo and see if you can reproduce? Do you have any existing node_modules on disk getting in the way? What OS are you using?

If python/node-gyp are the issue, I know that there are common workarounds for their build issues with node/npm. I wasn't aware we were using anything that required them, but if we are I'll try to investigate and include some FAQ on common remedies.

**Comment by ranasrule** [comment]
> 
> 
> I'm not 100% sure I follow the python and node-gyp requirements/output. I see different output when I clone a clean/new version of this repo and follow the install steps laid out in the readme. Try from a clean copy of the repo and see if you can reproduce? Do you have any existing node_modules on disk getting in the way? What OS are you using?
> 
> If python/node-gyp are the issue, I know that there are common workarounds for their build issues with node/npm. I wasn't aware we were using anything that required them, but if we are I'll try to investigate and include some FAQ on common remedies.
I downloaded the source again and tried and its working fine now. Thanks.
