### ISSUE TITLE
 Error: Cannot find module 'fibers' in meteor docker container.

### ISSUE THREAD

**Issue by Vishal568** [OHIF/Viewers#925]
When I deploy my ohif viewer meteor bundle in docker.
 Error: Cannot find module 'fibers'

```
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[2019-09-18 06:00:30] PM2 log: App [ohif-viewer] with id [0] and pid [169], exited with code [1] via signal [SIGINT]
[2019-09-18 06:00:30] PM2 log: Script /app/bundle/main.js had too many unstable restarts (16). Stopped. "errored"
[2019-09-18 06:00:31] PM2 log: 0 application online, exiting
[2019-09-18 06:00:31] PM2 log: [Watch] Stop watching ohif-viewer
[2019-09-18 06:00:31] PM2 log: Stopping app:ohif-viewer id:0
[2019-09-18 06:00:31] PM2 error: app=ohif-viewer id=0 does not have a pid
[2019-09-18 06:00:31] PM2 log: PM2 successfully stopped
```

How can I solve this issue? please anyone help me. what I do for a solution.

Thanks in advance.

**Comment by Vishal568** [comment]
The issue is solved.

When I place NPM fibers package in _app\bundle\programs\server\node_modules_ directory.
