### ISSUE TITLE
Your app is crashing. Here's the latest log: (OHIF Viewer)

### ISSUE THREAD

**Issue by steve7n** [OHIF/Viewers#97]
Hello,
I followed this: https://github.com/OHIF/Viewers/wiki/Getting-Started, but I get this: 

```
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
Started MongoDB.
Errors prevented startup:

While selecting package versions:
error: unknown package in top-level dependencies: ohif:polyfill
unknown package in top-level dependencies: ohif:core
unknown package in top-level dependencies: ohif:commands
unknown package in top-level dependencies: ohif:hotkeys
unknown package in top-level dependencies: ohif:header
unknown package in top-level dependencies: ohif:cornerstone
unknown package in top-level dependencies: ohif:viewerbase
unknown package in top-level dependencies: ohif:study-list
unknown package in top-level dependencies: ohif:dicom-services
unknown package in top-level dependencies: ohif:hanging-protocols
unknown package in top-level dependencies: ohif:metadata

Your application has errors. Waiting for file change.
```

I try running `meteor update`, but I get the same output.

Could I be doing something wrong? I am running Ubuntu.

Thanks a lot,

**Comment by steve7n** [comment]
I figure it out:

**1.**  In this line: `METEOR_PACKAGE_DIRS="../Packages" meteor --settings ../config/orthancDICOMWeb.json`

I changed this part: `METEOR_PACKAGE_DIRS="../Packages"`
to this: `METEOR_PACKAGE_DIRS="../Packages/"` (Added a final forward slash)

Then after running the line I got this error: 

`/home/ubuntu/Viewers/OHIFViewer/.meteor/local/build/programs/server/boot.js:391
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:36:9)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at packages/babel-runtime.js:143:15
    at packages/babel-runtime.js:154:3
    at /home/ubuntu/Viewers/OHIFViewer/.meteor/local/build/programs/server/boot.js:338:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.5.0.1vt8f1p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/ubuntu/Viewers/OHIFViewer/.meteor/local/build/programs/server/boot.js:158:5
    at /home/ubuntu/Viewers/OHIFViewer/.meteor/local/build/programs/server/boot.js:387:5
Exited with code: 1
Your application is crashing. Waiting for file change.`

**2.** Then I ran `meteor npm install --save babel-runtime` like the output said.

I ran:

`METEOR_PACKAGE_DIRS="../Packages/" meteor --settings ../config/orthancDICOMWeb.json` 

and everything worked, I could see OHIF Viewer on port 3000.

_But I could not load the studies_, and on the console I got this error:

`Unsafe attempt to load URL http://localhost:3000/packages/ohif_viewerbase/assets/icons.svg from frame with URL http://34.205.26.74:3000/viewer/1.3.46.670589.33.1.63630787808516494700001.5149394292224084497. Domains, protocols and ports must match.`

3. After doing some research I found that I had to add this `ROOT_URL=http://YOUR_IP:3000`, to this: 
`METEOR_PACKAGE_DIRS="../Packages/" meteor --settings ../config/orthancDICOMWeb.json`, 
so I finally ran it like this:

`METEOR_PACKAGE_DIRS="../Packages/" ROOT_URL=http://YOUR_IP:3000 meteor --settings ../config/orthancDICOMWeb.json`

Then everything worked great.

If you try to do it like me just remember to change `YOUR_IP` to your own IP Address.
